### ISSUE TITLE
DCGM_FI_DEV_GPU_UTIL doesn't show up with A100 GPU in MIG mode

### ISSUE THREAD

**Issue by cy-zheng** [NVIDIA/dcgm-exporter#105]
Hey there,

I want to make sure could I use dcgm-exporter to monitor the GPU utilization in A100 MIG mode?

I have a test on those MIG GPU instances, but I find that I cannot see DCGM_FI_DEV_*_UTIL metrics from dcgm-exporter. Even if I enable them in `/etc/dcgm-exporter/default-counters.csv`

My driver: `450.203.03`
My dcgm-exporter: `nvcr.io/nvidia/k8s/dcgm-exporter:2.4.6-2.6.10-ubuntu20.04`
My `nvidia-smi -L` output:
```
GPU 0: A100-SXM4-40GB (UUID: GPU-a810a1fc-9f46-0e6f-5cef-bf34c2248e12)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-a810a1fc-9f46-0e6f-5cef-bf34c2248e12/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-a810a1fc-9f46-0e6f-5cef-bf34c2248e12/2/0)
GPU 1: A100-SXM4-40GB (UUID: GPU-604c7a18-e7d0-02e0-723a-7578be840651)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-604c7a18-e7d0-02e0-723a-7578be840651/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-604c7a18-e7d0-02e0-723a-7578be840651/2/0)
GPU 2: A100-SXM4-40GB (UUID: GPU-213c841d-7181-629b-9a20-5c80fbd75ad9)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-213c841d-7181-629b-9a20-5c80fbd75ad9/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-213c841d-7181-629b-9a20-5c80fbd75ad9/2/0)
GPU 3: A100-SXM4-40GB (UUID: GPU-8345bdf0-6a9c-e1c1-5994-9e656aed3abc)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-8345bdf0-6a9c-e1c1-5994-9e656aed3abc/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-8345bdf0-6a9c-e1c1-5994-9e656aed3abc/2/0)
GPU 4: A100-SXM4-40GB (UUID: GPU-a583e23a-4957-5154-902b-a347482e0937)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-a583e23a-4957-5154-902b-a347482e0937/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-a583e23a-4957-5154-902b-a347482e0937/2/0)
GPU 5: A100-SXM4-40GB (UUID: GPU-730b3e2c-4b49-106c-9b0b-1ce13a10d125)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-730b3e2c-4b49-106c-9b0b-1ce13a10d125/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-730b3e2c-4b49-106c-9b0b-1ce13a10d125/2/0)
GPU 6: A100-SXM4-40GB (UUID: GPU-cc59bb72-3e96-09b6-02aa-c8c72fe191bf)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-cc59bb72-3e96-09b6-02aa-c8c72fe191bf/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-cc59bb72-3e96-09b6-02aa-c8c72fe191bf/2/0)
GPU 7: A100-SXM4-40GB (UUID: GPU-f57f1f74-7c11-6b82-c417-3544ef4c5d7b)
  MIG 3g.20gb Device 0: (UUID: MIG-GPU-f57f1f74-7c11-6b82-c417-3544ef4c5d7b/1/0)
  MIG 3g.20gb Device 1: (UUID: MIG-GPU-f57f1f74-7c11-6b82-c417-3544ef4c5d7b/2/0)
```
My docker run cmd:
`docker run -d --gpus all -p 9400:9400 --cap-add SYS_ADMIN nvcr.io/nvidia/k8s/dcgm-exporter:2.4.6-2.6.10-ubuntu20.04`

**Comment by cy-zheng** [comment]
If the metrics DCGM_FI_DEV_*_UTIL are not supported on MIG mode, then how could I get the GPU utilization per GPU instance?

**Comment by nikkon-dev** [comment]
@cy-zheng ,

The DCGM_FI_DEV_GPU_UTIL metric is not supported in MIG mode. 

You need to use DCP set of metrics - DCGM_FI_PROF*.

You could see the example at the bottom of this file: https://github.com/NVIDIA/dcgm-exporter/blob/main/etc/dcp-metrics-included.csv

Documentation about the DCP metrics meaning: https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#profiling-metrics

**Comment by esparig** [comment]
Please, which specific metrics are available in MIG mode?
