### ISSUE TITLE
Exporting processes with DCGM

### ISSUE THREAD

**Issue by saifhaq** [NVIDIA/dcgm-exporter#109]
I would love to export the different processes that can be seen using nvidia-smi. I have got the dcgm_exporter working in a docker container running on a bare metal host, with logs being stored in a central Prometheus server. 
 
I do not understand how I would be able to export the running process names, their PID, and respective gpu memory usage, all of which can be seen from nvidia-smi.  

I can see there is an available field identifier DCGM_FI_PROCESS_NAME; however when I try to add this to my /etc/dcgm-exporter/dcp-metrics-included.csv; the exporter crashes and exports nothing.

If anyone could provide any insight I would greatly appreciate it!! 

Thanks :pray:

**Comment by suchisur** [comment]
Any follow ups on this?

**Comment by ettelr** [comment]
Is it in any roadmap?

**Comment by nikkon-dev** [comment]
I'm sorry, but you cannot use the DCGM_FI_PROCESS_NAME metric as it is. The process name should be a label in a per-PID-GPU-utilization metric. Also, you must enable a particular mode (Accounting mode in NVML or DCGM stats) before that data becomes available. Unfortunately, dcgm-exporter does not currently have the functionality to allow per-PID stats. We may consider adding this feature, but we have not made any specific plans.
