### ISSUE TITLE
The way to understand additional dcgm-exporter Prometheus metric type

### ISSUE THREAD

**Issue by k0nstantinv** [NVIDIA/dcgm-exporter#116]
Hi! I'm trying to enable additional metrics in the exporter. According to the doc section [Changing Metrics](https://github.com/NVIDIA/dcgm-exporter#changing-metrics) I need to add csv metric description here `/etc/dcgm-exporter/default-counters.csv`, but to be able to enable it I need to know Prometheus type of a metric. 

Is there a way somehow understand metric type from that page below?
https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html

For example: [DCGM_FI_DEV_NAME](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html#c.DCGM_FI_DEV_NAMEl)

**Comment by nikkon-dev** [comment]
Hi @k0nstantinv,

We do not have a direct list of the dcgm-Prometheus or dcgm-collectd types' correspondence.
You could get some ideas from this collectd [script](https://github.com/NVIDIA/DCGM/blob/f6fe5654b780873da528b84cb3d7de10d7abe0d1/testing/python3/dcgm_fields_collectd.py#L43).

The metric in your example cannot be represented as a Prometheus metric value and instead should be used as a Prometheus metric label. See an example [here](https://github.com/NVIDIA/dcgm-exporter/blob/e2ba7f830e66b85578059d78860d3ee55ea49403/etc/dcp-metrics-included.csv#L68).

I hope that will help you.

WBR,
Nik

**Comment by k0nstantinv** [comment]
@nikkon-dev thanks a lot!  One notice about enabling labels. One of the latest release of exporter required to be able to enable any label. For example enabling labels on `2.1.4-2.2.0` ends up fatal
```
time="2022-11-02T10:41:03Z" level=fatal msg="Could not find Prometheus metry type label"
```
