### ISSUE TITLE
Error with chart install

### ISSUE THREAD

**Issue by tapter-mwm** [NVIDIA/dcgm-exporter#125]
Hi, 

I have been struggling with installing dcgm-exporter chart on my k8s cluster for a while. I've followed the provided documentation to install it with helm but the pods are endlessly restarting with this error message: `Failed to initialize NVML` `Error starting nv-hostengine: DCGM initialization error`

Chart version: 3.1.3-3.1.2-ubuntu20.04
Kube cluster version: 1.23.11-gke.300
CUDA drivers version: 510.47.03
GPU type: NVIDIA T4

Does someone have faced the same issue ?

**Comment by nikkon-dev** [comment]
Hi @tapter-mwm,

Are you able to use GPUs in your pods? Does `nvidia-smi` work inside a pod?

The error you observe usually means the k8s is not properly configured to use GPUs

**Comment by tapter-mwm** [comment]
Yeah the GPUs are in use by several workloads. Although, the `nvidia-smi` command is not known in the pods. But the GPUs works fine

**Comment by harjitdotsingh** [comment]
I'm also running in to the same issue I'm on Nvidia A100 80G. Your pods may not know this but you should be able to run the command from the nvidia-mig-manager pod.

**Comment by tapter-mwm** [comment]
Hi, 

Is it possible to have some follow up ? 

My GPUs are working as expected but still not able to install dcgm-exporter. 

Thank you

**Comment by tapter-mwm** [comment]
![Capture d’écran 2023-01-17 à 09 21 27](https://user-images.githubusercontent.com/98518973/212845491-58f8d907-834e-4336-9b87-92fd70562215.png)

I did not myself install the gpu operator. However I use Time Sharing feature from gke which seems to aim toward the same goal (please correct me if I'm wrong)

When I try to deploy the `dcgm-exporter` chart I get 5 pods, which make sense, since I have five GPUs nodes running

**Comment by tapter-mwm** [comment]
Yeah I already tried that but same output
<img width="1056" alt="Capture d’écran 2023-01-18 à 09 24 38" src="https://user-images.githubusercontent.com/98518973/213120632-4d8772ee-8557-47c4-9a7c-286898891819.png">

**Comment by harjitdotsingh** [comment]
This one is easy to fix.  You will have to get that file and then add this to the file
`securityContext:
       capabilities:
         add:
           - SYS_ADMIN`
           that will give it the permission to run.

**Comment by tapter-mwm** [comment]
<img width="838" alt="Capture d’écran 2023-01-19 à 15 55 33" src="https://user-images.githubusercontent.com/98518973/213475039-c8f517f0-c195-43c5-b195-bacf28c7a20d.png">

Didn't fix the thing ...

**Comment by harjitdotsingh** [comment]
can you see how many pods are running ?

**Comment by tapter-mwm** [comment]
Yeah I still have 5 pods running, still in CrashLoopBackOff
