### ISSUE TITLE
Fatal error while running DCGM Exporter on AKS

### ISSUE THREAD

**Issue by harjitdotsingh** [NVIDIA/dcgm-exporter#126]
I have deployed GPU operator and we are trying  timeslicing for GPU, that seems to works fine. But when we use the instructions to run DCGM using [this](https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/dcgm-exporter.html) page, we get the following error

`time="2023-01-05T16:23:09Z" level=info msg="Starting dcgm-exporter"
time="2023-01-05T16:23:09Z" level=info msg="DCGM successfully initialized!"
time="2023-01-05T16:23:09Z" level=info msg="Collecting DCP Metrics"
time="2023-01-05T16:23:09Z" level=info msg="No configmap data specified, falling back to metric file /etc/dcgm-exporter/dcp-metrics-included.csv"
time="2023-01-05T16:23:09Z" level=info msg="Initializing system entities of type: GPU"
time="2023-01-05T16:23:09Z" level=fatal msg="Failed to watch metrics: Error watching fields: The third-party Profiling module returned an unrecoverable error"`

The dcgm-exporter pods have the  `CrashLoopBackOff `

**Comment by glowkey** [comment]
You originally stated that you deployed gpu-operator. dcgm-exporter is deployed as part of gpu-operator (see [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#gpu-telemetry). Did you deploy an additional dcgm-exporter?

**Comment by glowkey** [comment]
Yes. Take a look at this thread for something similiar: https://github.com/NVIDIA/gpu-operator/issues/195

**Comment by harjitdotsingh** [comment]
installed the gpu-opertor with the following options but still not seeing any metrics in Prometheus.


`helm install gpu-operator nvidia/gpu-operator -n gpu-operator \
--set devicePlugin.config.name=time-slicing-config \
--set dcgmExporter.config.name=metrics-config \
--set dcgmExporter.env[0].name=DCGM_EXPORTER_COLLECTORS \
--set dcgmExporter.env[0].value=/etc/dcgm-exporter/dcgm-metrics.csv \
--set extraConfigMapVolumes[0].name=exporter-metrics-volume \
--set extraConfigMapVolumes[0].configMap.name=exporter-metrics-config-map \
--set extraEnv[0].name=DCGM_EXPORTER_CONFIGMAP_DATA \
--set extraEnv[0].value=default:exporter-metrics-volume
`

**Comment by harjitdotsingh** [comment]
We can close this
