### ISSUE TITLE
nvidia.com/gpu: 1

### ISSUE THREAD

**Issue by hecheng64** [NVIDIA/dcgm-exporter#127]
If my pod is not configured with nvidia.com/gpu: 1, specific indicator values cannot be collected。 The pod must be configured with nvidia.com/gpu: 1？

**Comment by hecheng64** [comment]
> Yes, Kubernetes makes certain labels available only when the pod is configured with "nvidia.com/gpu".

If the pod is configured with nvidia.com/gpu, the gpu resources are exclusively occupied by the pod (only one gpu card), and the statistics of different pods indicators for each gpu card cannot be reached

**Comment by hecheng64** [comment]
> Yes, Kubernetes makes certain labels available only when the pod is configured with "nvidia.com/gpu".

The dcgm exporter can collect the memory size of each process and the gpu utilization rate of each process? I feel that I can only collect the memory size and gpu utilization of this card

**Comment by glowkey** [comment]
Correct, dcgm exporter does not report process utilization but gpu and pod utilization.

**Comment by hecheng64** [comment]
> Correct, dcgm exporter does not report process utilization but gpu and pod utilization.

Is there a good way that a GPU card can run multiple pods and collect indicators

**Comment by glowkey** [comment]
We are looking into enhancements to better enable dcgm exporter reporting with gpu time slicing but that is still in the planning stages.
