### ISSUE TITLE
Filtering deployment to certain nodes

### ISSUE THREAD

**Issue by coleary-hyperscience** [NVIDIA/dcgm-exporter#131]
I apologize if this question has already been answered, but I cannot find anything about it in [the documentation](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/archive/1.9.0/install-gpu-operator.html#chart-customization-options), Readmes, or other issues.

## Setup
I have an EKS cluster which uses some m5 and p1 nodes. The m5 nodes don't have GPU enabled and so when I try install the GPU exporter using `helm install dcgm-exporter gpu-helm-charts/dcgm-exporter -n monitoring` I get a dcgm-exporter pod in a `CrashLoopBackOff`. All of my GPU nodes have a dcgm exporter which work just fine though.

## Problem
Is there a way to get the dcgm exporter (installed via helm) to only deploy on nodes with GPU capabilities? Potentially though nodeAffinity? And what parameters would I set to allow this?

**Comment by nikkon-dev** [comment]
@coleary-hyperscience,

Most likely, you need to take a look at selectors in the [values.yaml](https://github.com/NVIDIA/dcgm-exporter/blob/main/deployment/values.yaml)

**Comment by coleary-hyperscience** [comment]
:doh: for some reason I was looking at the values file for the [GPU-Operator](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml) to no avail. This file does work for me (although for some reason it doesn't allow for nodeAntiAffinity). Thank you!
