### ISSUE TITLE
Broken go.mod

### ISSUE THREAD

**Issue by starry91** [NVIDIA/dcgm-exporter#132]
I am trying to use the [dcgmexporter](https://github.com/NVIDIA/dcgm-exporter/tree/main/pkg/dcgmexporter) go package with `go 1.19` and get the following error when trying to install it locally.
```
$:/myHome/gpu_metric_testing/metroid$ go get github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter
go: github.com/NVIDIA/dcgm-exporter@v0.0.0-20230114163322-8b8854b15eb7 requires
        k8s.io/kubernetes@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
$:
```
Is this a bug? Also, in [go.mod](https://github.com/NVIDIA/dcgm-exporter/blob/main/go.mod#L43) why are the packages first added under [require](https://go.dev/ref/mod#go-mod-file-require) and then again [replaced](https://go.dev/ref/mod#go-mod-file-replace) with other versions? Instead why not directly put the relevant package versions under the [require](https://go.dev/ref/mod#go-mod-file-require) directive?

**Comment by glowkey** [comment]
The repo is setup for our build pipeline, which involves cloning and then running the relevant 'make' commands to build and test. I just verified that the 'make' steps are functional with 1.19.

**Comment by starry91** [comment]
@glowkey Apologies, I should have been more verbose earlier. Like you pointed, the build process does work for me too. But the issue comes up only when I try to use the public package [dcgmexporter](https://github.com/NVIDIA/dcgm-exporter/tree/main/pkg/dcgmexporter) as dependency module in my application. To add more context, I am trying to build an exporter application which writes a bunch of dcgm metrics to a file (preserving the field types). So, wanted to build something on top of [dcgmexporter](https://github.com/NVIDIA/dcgm-exporter/tree/main/pkg/dcgmexporter) since it already has most of the boilerplate code.

**Comment by glowkey** [comment]
Thank you for the additional information. I don't think this qualifies as a bug. If you have changes for dcgm-exporter that work around this issue for your project please open a PR and we will evaluate it.
