### ISSUE TITLE
Pod label not coming up for some pod

### ISSUE THREAD

**Issue by tsingh-asapp** [NVIDIA/dcgm-exporter#138]
We have deployed the dcgm exporter to get the gpu related metrics. We are able to get the metric, but for some application the pod label is not coming up ( but for some we are getting the label ) and they are running in same namespace.
`Image version -- nvcr.io/nvidia/k8s/dcgm-exporter:2.3.1-2.6.0-ubuntu20.04`
We are running this on EKS 1.21 version.
and we using the "uid" to get the GPU label.
```
            - name: DCGM_EXPORTER_KUBERNETES
              value: 'true'
            - name: DCGM_EXPORTER_LISTEN
              value: ':9400'
            - name: DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE
              value: uid
```

**Comment by nikkon-dev** [comment]
@tsingh-asapp,

Could you provide raw output from the dcgm-exporter monitoring (Prometheus format) for both cases?

Could you also clarify the dcgm-exporter command line arguments you specify in the `values.yaml` file (I assume you are using Helm)?

**Comment by tsingh-asapp** [comment]
@nikkon-dev i found the issue, The is related to the  `nvidia.com/gpu: '1'` . As i understand from the code , this is need by the exporter to identify the application which use the gpu. This value in required in the limit section of the pod resource at pod/deployment template.
We can close the case
