### ISSUE TITLE
Why is DCGM_FI_DEV_MEM_COPY_UTIL not equal to DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_FREE+DCGM_FI_DEV_FB_USED)?

### ISSUE THREAD

**Issue by IsQiao** [NVIDIA/dcgm-exporter#147]
Why is `DCGM_FI_DEV_MEM_COPY_UTIL` not equal to `DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_FREE+DCGM_FI_DEV_FB_USED)` ?

![image](https://user-images.githubusercontent.com/8536046/226552571-0496c979-42f1-478a-ae24-94db6978efa7.png)

**Comment by glowkey** [comment]
DCGM_FI_DEV_MEM_COPY_UTIL is the percent of time over the past sample period during which global (device) memory was being read or written. The other metrics are reported in MB and are not percentages.

**Comment by IsQiao** [comment]
DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_FREE+DCGM_FI_DEV_FB_USED)
this expression is the percent memory util.

**Comment by nikkon-dev** [comment]
@IsQiao,
 
It seems like you are confusing read/write usage with allocation. For example, if we allocate just 1Mb of memory and spend the entire cycle reading/writing that 1Mb, then the DCGM_FI_DEV_MEM_COPY_UTIL will show 100% utilization, but the DCGM_FI_DEV_FB_USED will only show 1Mb out of gigabytes.

**Comment by IsQiao** [comment]
Ok, I understand. Thanks.
