### ISSUE TITLE
Does DCP metric （DCGM_FI_PROF_*）support RTX 3090 GPUs?

### ISSUE THREAD

**Issue by asaderasxyz** [NVIDIA/dcgm-exporter#152]
I am running dcgm-exporter on a single GPU (RTX 3090).  I can't seem to get profiling metrics to show up, though other metrics show up fine.

It looks like the profiling module fails to load:

root@7dd70341bca3:/# dcgmi modules -l
+-----------+--------------------+--------------------------------------------------+
| List Modules                                                                      |
| Status: Success                                                                   |
+===========+====================+==================================================+
| Module ID | Name               | State                                            |
+-----------+--------------------+--------------------------------------------------+
| 0         | Core               | Loaded                                           |
| 1         | NvSwitch           | Loaded                                           |
| 2         | VGPU               | Not loaded                                       |
| 3         | Introspection      | Not loaded                                       |
| 4         | Health             | Not loaded                                       |
| 5         | Policy             | Not loaded                                       |
| 6         | Config             | Not loaded                                       |
| 7         | Diag               | Not loaded                                       |
| 8         | Profiling          | Failed to load                                   |
+-----------+--------------------+--------------------------------------------------+

**Comment by nikkon-dev** [comment]
@asaderasxyz,

No, the RTX class of GPUs does not support DCGM_FI_PROF* metrics.
