### ISSUE TITLE
ecc errors metrics

### ISSUE THREAD

**Issue by jaywlm** [NVIDIA/dcgm-exporter#157]
dcgm-exporter support metrics below ?

1. ecc.errors.uncorrected.volatile.dram
2. ecc.errors.uncorrected.volatile.sram
3. ecc.errors.uncorrected.aggregate.dram
4. ecc.errors.uncorrected.aggregate.sram

**Comment by nikkon-dev** [comment]
@jaywlm,

Please look at the available fields [here](https://github.com/NVIDIA/DCGM/blob/master/dcgmlib/dcgm_fields.h). You need fields whose names start with DCGM_FI_DEV_ECC
