### ISSUE TITLE
Does dcgm3.0 version support NvLink metric collection?

### ISSUE THREAD

**Issue by chjar** [NVIDIA/dcgm-exporter#162]
I have run the docker image nvcr.io/nvidia/k8s/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 with the following command: "sudo docker run -ti --gpus all --privileged --network=host --pid=host --cap-add=sys_ptrace nvcr.io/nvidia/k8s/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04". 

INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling back to metric file /etc/dcgm-exporter/default-counters.csv
INFO[0000] Initializing system entities of type: GPU
INFO[0001] Initializing system entities of type: NvSwitch
INFO[0001] Not collecting switch metrics: no switches to monitor
INFO[0001] Initializing system entities of type: NvLink
INFO[0001] Not collecting link metrics: no switches to monitor
INFO[0001] Pipeline starting
INFO[0001] Starting webserver

The logs show that dcgm-exporter successfully initialized and started collecting DCP metrics. However, I noticed that the nvLink and nvswitch metrics are not being collected.

I looked into the code and found that the issue is caused by the function "getEntityGroupEntities" in "device_info.go", where the count variable is 0, resulting in the following error message being printed: "Not collecting link metrics: no switches to monitor".

I noticed that the feature list for tag 3.1.3-3.1.2 includes support for NvSwitch/NvLink metric collection. 

Thank you for your attention to this matter.

**Comment by glowkey** [comment]
Which metrics are missing(the specific fields)? Depending on which metrics are missing the steps to troubleshoot will be different.

**Comment by chjar** [comment]
> Which metrics are missing(the specific fields)? Depending on which metrics are missing the steps to troubleshoot will be different.
I want to know what caused this log message to be printed，Not collecting switch metrics: no switches to monitor

**Comment by chjar** [comment]
> Which metrics are missing(the specific fields)? Depending on which metrics are missing the steps to troubleshoot will be different.

I want to know what caused this log message to be printed，Not collecting switch metrics: no switches to monitor

**Comment by glowkey** [comment]
By default the dcgm-exporter container does not have access to nvswitches and libnvidia-nscq needed to monitor nvswitch metrics. That is why you are seeing the message "no switches to monitor", they are not accessible within the dcgm-exporter container. There are 2 ways to work around this. 1) start DCGM agent on the host and use the dcgm-exporter "-r HOST:PORT" option (see https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/dcgm-exporter.html#connecting-to-an-existing-dcgm-agent). 2) Mount the necessary nvswitch devices and libnvidia-nscq files within the dcgm-exporter container.

**Comment by lyj8330328** [comment]
How to collect nvlink metrics? I had the same problem。How to mount the nvswitch devices and libnvidia-nscq files within the dcgm-exporter container?

**Comment by lyj8330328** [comment]
> By default the dcgm-exporter container does not have access to nvswitches and libnvidia-nscq needed to monitor nvswitch metrics. That is why you are seeing the message "no switches to monitor", they are not accessible within the dcgm-exporter container. There are 2 ways to work around this. 1) start DCGM agent on the host and use the dcgm-exporter "-r HOST:PORT" option (see https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/dcgm-exporter.html#connecting-to-an-existing-dcgm-agent). 2) Mount the necessary nvswitch devices and libnvidia-nscq files within the dcgm-exporter container.

How to mount the nvswitch devices and libnvidia-nscq files within the dcgm-exporter container?
