### ISSUE TITLE
How to troubleshoot missing fields?

### ISSUE THREAD

**Issue by iliakur** [NVIDIA/dcgm-exporter#163]
Hi, thanks for the tool!

We used [the configuration file](https://github.com/NVIDIA/dcgm-exporter/blob/main/etc/default-counters.csv) to enable the collection of some extra fields.

When we perform a curl request to the prometheus endpoint, however, we are missing the following enabled fields:

- DCGM_FI_DEV_MEMORY_TEMP
- DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS
- DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS
- DCGM_FI_DEV_ROW_REMAP_FAILURE
- DCGM_FI_PROF_PCIE_TX_BYTES
- DCGM_FI_PROF_PCIE_RX_BYTES
- DCGM_FI_DEV_FAN_SPEED

After some digging we made the following observations:

1. The exporter package has [generic filtering](https://github.com/iliakur/dcgm-exporter/blob/2d053d52c6af0c632c271c4bf94de42c91828605/pkg/dcgmexporter/gpu_collector.go#L170) for null values. This suggests that the missing fields were not available from the underlying drivers.
2. For DCGM_FI_DEV_FAN_SPEED we couldn't find any fan sensors. I guess that explains why it's missing.
3. Fields related to remapping may have been missing because no remapping had been triggered.
4. We still don't know why the PCIE fields are missing.

Here's our question:
How do you recommend that dcgm-exporter users troubleshoot missing fields? Is there some diagnostic/debugging tool we can use instead of hunting down each field (group) differently?

Thanks in advance!

**Comment by glowkey** [comment]
The DCGM log located inside the dcgm-exporter container at  `/var/log/nv-hostengine.log` will contain information for each requested fieldId (search using the integer value of the fieldId). You can set the container env variable `__DCGM_DBG_LVL=DEBUG` to dump verbose logging to that file.
