### ISSUE TITLE
Get DCGM_FI_DEV_PCIE_TX_THROUGHPUT metric failed 

### ISSUE THREAD

**Issue by Lzhang-hub** [NVIDIA/dcgm-exporter#167]
I Builded from Source and run dcgm-exporter on host.
```
$ git clone https://github.com/NVIDIA/dcgm-exporter.git
$ cd dcgm-exporter
$ make binary
$ sudo make install
...
$ dcgm-exporter &
$ curl localhost:9400/metrics
```
But I can not find DCGM_FI_DEV_PCIE_TX_THROUGHPUT metrics and DCGM_FI_DEV_PCIE_RX_THROUGHPUT.

Condition:
GPU: T4
dcgm-exporter version: 3.1.8-3.1.5
nv-hostengine: 3.1.8

**Comment by nikkon-dev** [comment]
@Lzhang-hub,

Are those options enabled in the .csv configuration file for dcgm-exporter that you're using? The default-counter.csv files in the repository have them enabled, but dcp-metrics-included.csv disables them by default.

**Comment by Lzhang-hub** [comment]
I use the .csv configuration file in the repository.
![image](https://github.com/NVIDIA/dcgm-exporter/assets/57925599/a2b5e326-f873-4150-82da-a9c65ada7295)

And I find `Not collecting switch metrics: no switches to monitor` in start log, Is it because can't find Nvswitch on the host?
```
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling back to metric file ./etc/default-counters.csv
INFO[0000] Initializing system entities of type: GPU
INFO[0000] Initializing system entities of type: NvSwitch
INFO[0000] Not collecting switch metrics: no switches to monitor
INFO[0000] Initializing system entities of type: NvLink
INFO[0000] Not collecting link metrics: no switches to monitor
INFO[0000] Pipeline starting
INFO[0000] Starting webserver
```
Beside, I try to get PCIE metrics through dcgmi command accord filed id https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html:

`dcgmi dmon -d 100 -e 200`
Result is N/A
![image](https://github.com/NVIDIA/dcgm-exporter/assets/57925599/73cbaa43-eab9-4a97-95d1-119a87b9066e)

**Comment by Lzhang-hub** [comment]
@nikkon-dev Can you give me some advices, Thanks very much!

**Comment by zabiziz** [comment]
I'm having the same issue with a server with 8xA100 SXM and CentOS 7.9

**Comment by Lzhang-hub** [comment]
@zabiziz If you want to collect metrics DCGM_FI_DEV_PCIE_RX_THROUGHPUT ,you can use DCGM_FI_PROF_PCIE_TX_BYTES1009 instead  DCGM_FI_DEV_PCIE_RX_THROUGHPUT, you can find the document in https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html
![image](https://github.com/NVIDIA/dcgm-exporter/assets/57925599/d3b3811d-3240-46c2-9ba1-02b1604bc36e)

**Comment by zabiziz** [comment]
> @zabiziz If you want to collect metrics DCGM_FI_DEV_PCIE_RX_THROUGHPUT ,you can use DCGM_FI_PROF_PCIE_TX_BYTES1009 instead DCGM_FI_DEV_PCIE_RX_THROUGHPUT, you can find the document in https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html ![image](https://user-images.githubusercontent.com/57925599/245653286-d3b3811d-3240-46c2-9ba1-02b1604bc36e.png)

Thank you. 
It worked!

**Comment by yule-sun** [comment]
I have the same question , i found the metrics DCGM_FI_PROF_PIPE_TENSOR_ACTIVE in my docker's file /etc/dcgm-exporter/dcp-metrics-included.csv , but i cann't get the value in the prometheus 
![image](https://github.com/NVIDIA/dcgm-exporter/assets/37107125/ba386c3f-55fc-45ec-a191-e02922981426)
![image](https://github.com/NVIDIA/dcgm-exporter/assets/37107125/f0bb6336-138e-47a0-ab94-c9799b8fe761)

**Comment by nikkon-dev** [comment]
@yule-sun,

dcgm-exporter does not use the dcp-metrics-included.csv by default. Its usage should be specified via the command line argument: `-f /etc/dcgm-exporter/dcp-metrics-included.csv`. If the command line argument `-f` is not provided and no ConfigMap (in k8s environment) is used, the /etc/dcgm-exporter/default-counters.csv file is used by default.

Also, the DCP metrics are not available for all GPUs, only datacenter grade (Tesla) Volta or newer arch GPUs.
For not-supported GPUs, the DCP metrics are not reported even if enabled.
