### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by ralbertazzi** [NVIDIA/dcgm-exporter#176]
Docker [image size on Dockerhub](https://hub.docker.com/r/nvidia/dcgm-exporter/tags) has been growing a lot in the last two years, in particular the `amd64` platform: from 200 MB to 1 GB, and this is only the compressed size! I'm sure I don't need to explain too much why bigger image sizes are worse, but here's a couple of example:
- Docker pulls become much slower, thus slowing down the startup of new nodes
- You need bigger disk sizes to accomodate the image, which results in a more expensive infrastructure

Is there anything that can be done to make the image smaller?

EDIT: [this](https://github.com/NVIDIA/dcgm-exporter/blob/main/docker/Dockerfile.ubuntu20.04#L16-L17) is the layer that seems to bring most of the image size

EDIT 2: after a proper investigation with [dive](https://github.com/wagoodman/dive) it looks like most of the space taken by that layer comes from these two files (tag: `dcgm-exporter:3.1.8-3.1.5-ubuntu20.04`):
- `/usr/lib/aarch64-linux-gnu/libdcgm_cublas_proxy11.so` (333 MB)
- `/usr/lib/aarch64-linux-gnu/libdcgm_cublas_proxy12.so` (475 MB)

**Comment by HennerM** [comment]
When I install `datacenter-gpu-manager=1:3.3.9` in a Docker image, these shared objects are 
* 547.7 MiB ibdcgm_cublas_proxy11.so
* 488.2 MiB libdcgm_cublas_proxy12.so
which totals to more than 1GB. Is there a way to avoid pulling these in?
