### ISSUE TITLE
What are these constraints?

### ISSUE THREAD

**Issue by irvingans** [NVIDIA/dcgm-exporter#184]
https://github.com/NVIDIA/dcgm-exporter/blob/cffaeb8102bc50ba90fed17c2a9cad8900c3f5fa/deployment/templates/metrics-configmap.yaml#L39
Hi ,
I saw there are some constraints here https://github.com/NVIDIA/dcgm-exporter/blob/main/deployment/templates/metrics-configmap.yaml in below line of # Errors and violations. But are there any details of these constraints? Or where can I get the list of these constraints?

1.sync-boost constraints
2.board limit constraints
3.low utilization (in us)
4.reliability constraints

**Comment by glowkey** [comment]
These are pulled from NVML. You can find more information here: https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceStructs.html#group__nvmlDeviceStructs_1ga2f5ef75e515058513a54e8575b80330

**Comment by irvingans** [comment]
Hi @glowkey , regarding the NVML link you presented, I have got three more doubts:
![image](https://github.com/NVIDIA/dcgm-exporter/assets/70804456/eab6598e-6bbb-46fc-869f-0b6bf2c15bec)
1. What is sync boost and why it can cause GPU to be below application clock?
2. Why can low utilization cause GPU to be below application clock?
3. What is board reliability limit?

**Comment by glowkey** [comment]
Rather than paste internet search results here, do you have a specific use-case you are trying to enable where you believe these might be useful?

**Comment by irvingans** [comment]
Not really , I am just trying to understand dcgm-exporter.
