### ISSUE TITLE
how to get cuda version?

### ISSUE THREAD

**Issue by sladkehs** [NVIDIA/dcgm-exporter#189]
I am new to Prometheus query. Is there a query that can find out the cuda version from dcgm exporter?

**Comment by nikkon-dev** [comment]
@sladkehs,

There are several fields that you may need to enable: 
- [DCGM_FI_CUDA_DRIVER_VERSION](https://github.com/NVIDIA/DCGM/blob/4e0a87a8c7a9af99e0d911c491d9a65204f1a30e/dcgmlib/dcgm_fields.h#L237)
- [DCGM_FI_DEV_CUDA_COMPUTE_CAPABILITY](https://github.com/NVIDIA/DCGM/blob/4e0a87a8c7a9af99e0d911c491d9a65204f1a30e/dcgmlib/dcgm_fields.h#L310C7-L310C7)

In any case, DCGM will only report the Cuda driver version (i.e., if you have a full Cuda SDK installed, its version will not be shown).
