### ISSUE TITLE
Feature request: provide an url for reset `DCGM_FI_DEV_XID_ERRORS` to 0

### ISSUE THREAD

**Issue by zdyang** [NVIDIA/dcgm-exporter#190]
Hi, thank you for your work!

I have been using `dcgm-exporter` to expose the metrics in our GPU cluster to Prometheus, and it has been working as expected.

The issue I encountered is related to the `DCGM_FI_DEV_XID_ERRORS`, which represents the latest XID error. My concern is that if two consecutive errors with the same XID error code occur, `dcgm-exporter `is unable to detect the later one, especially for certain user program errors (such as xid = 31).

Currently, the workaround for this is to restart the `dcgm-exporter` pod, but this approach is not convenient or reasonable. It would be great if we could provide a RESTful API to reset the `DCGM_FI_DEV_XID_ERRORS` to 0.

**Comment by homily707** [comment]
Is this resolved? how to reset

**Comment by homily707** [comment]
FYI，https://github.com/NVIDIA/dcgm-exporter/pull/239 this resolved
