### ISSUE TITLE
Could we make socketDir configurable

### ISSUE THREAD

**Issue by wengyao04** [NVIDIA/dcgm-exporter#192]
Hi, could we make [socketDir](https://github.com/NVIDIA/dcgm-exporter/blob/main/pkg/dcgmexporter/kubernetes.go#L35) configurable ? The default kubelet socket dir is `/var/lib/kubelet/pod-resources` . However, we configure kubelet in a different directory. 

We can set up a symbolic link to point to our pod-resources directory, but it would be nice to let users configure the kubelet socket dir ?

Thanks

**Comment by rnertney** [comment]
Hi @wengyao04, thanks for the suggestion! We have taken this feedback and will try to get it added to our roadmap.

**Comment by wengyao04** [comment]
Hi @rnertney Thank you ! We want to contribute this change. Could we attend the community meeting and is there a slack channel we can join ?

BTW: what's the release cycle of dcgm-exporter ?

**Comment by glowkey** [comment]
The process for contributing is documented here: https://github.com/NVIDIA/dcgm-exporter/blob/main/CONTRIBUTING.md (no meetings or slack channel). Releases usually follow DCGM itself, every few months, but exceptions are made when needed.

**Comment by nvvfedorov** [comment]
Done with merged PR: https://github.com/NVIDIA/dcgm-exporter/pull/199.
