### ISSUE TITLE
Cannot get *most* metrics on Kubernetes hosted on OpenStack VM

### ISSUE THREAD

**Issue by drew-viles** [NVIDIA/dcgm-exporter#193]
# The Problem

I have seen multiple requests much like this one so it's more a request for guidance really.

We have an OpenStack Cluster which contains a bunch of bare-metal nodes with A100s in them - these are configured for MIG.
We VMs deployed on this on which we have created a Kubernetes Cluster.
We can use the GPUs on this cluster perfectly - no issue at all.

The problem I'm facing is that I cannot get mode of the metrics out of the DCGM exporter when using the GPU Operator.

The only ones being shown in Prometheus are:
```
    DCGM_FI_DEV_FB_FREE
    DCGM_FI_DEV_FB_USED
    DCGM_FI_DEV_MEM_CLOCK
    DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL
    DCGM_FI_DEV_SM_CLOCK
    DCGM_FI_DEV_XID_ERRORS
    DCGM_FI_DEV_VGPU_LICENSE_STATUS
```

# What I've done

I've jumped into one of the `DCGM Exporter` Pods and run `nvidia-smi`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID A100DX-2-20C   On   | 00000000:00:05.0 Off |                   On |
| N/A   N/A    P0    N/A /  N/A |                  N/A |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  0    0   0   0  |      0MiB / 18411MiB | 28      0 |  2   0    1    0    0 |
|                  |      0MiB /  4096MiB |           |                       |
+------------------+----------------------+-----------+-----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

As you can see there is a lot of `N/A` fields where I'd expect there to be data.

I have seen in this issue https://github.com/NVIDIA/dcgm-exporter/issues/144 that @nikkon-dev mentioned something about splitting the `dcgm exporter` and one having to be privileged when using MIG. I did find buried deep in a doc somewhere which I have since lost the link to that metrics were reduced inside a guest VM - is this what I'm hitting here?

Is there any docs on how this works/what is expected to get this data exposed or is it just not possible in my scenario?

FWIW I've also tried changing the `dcgm-metrics.csv` that's passed in to match [this](https://github.com/NVIDIA/dcgm-exporter/blob/main/etc/dcp-metrics-included.csv) but this hasn't work, evidently because some data is missing at the pod level (DCGM Exporter)

*Additional Information*

```
root@nvidia-dcgm-exporter-bdrst:/# echo $NVIDIA_DRIVER_CAPABILITIES
compute,utility,compat32

root@nvidia-dcgm-exporter-bdrst:/# ldconfig -p | grep -i libnvidia-ml.so
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
        libnvidia-ml.so.1 (libc6) => /usr/lib/i386-linux-gnu/libnvidia-ml.so.1

root@nvidia-dcgm-exporter-bdrst:/# ls -l /usr/lib/i386-linux-gnu/libnvidia-ml.so.525.85.05
-rwxr-xr-x 1 root root 1772204 Sep  4 15:54 /usr/lib/i386-linux-gnu/libnvidia-ml.so.525.85.05
```

Let me know if you need anything else from my side.

**Comment by drew-viles** [comment]
Hi, @nvvfedorov can you confirm how has this been completed or if it's just not something that can be done please?

**Comment by nvvfedorov** [comment]
@drew-viles , I closed the issue as inactive for an extended period.  If you confirm that the problem still exists, I will re-open it.

**Comment by drew-viles** [comment]
It's only really inactive as no one addressed it. The problem does still exist though. I'm not sure if it's one of those things where the metrics I'm after just cannot be accessed from the pod level in a Kubernetes cluster though. It may not be a DCGM exporter problem.

**Comment by nvvfedorov** [comment]
Thank you for confirming. I reopen the issue.

**Comment by nvvfedorov** [comment]
@drew-viles, Let's start from the beginning.  Can you connect to the dcgm-exporter pod and run `dcgmi discovery -l`? The first step is to make sure, that dcgm sees your GPUs.

**Comment by drew-viles** [comment]
Unfortunately I have now switched jobs now and as such, no longer have access to the NVIDIA GPUs but I've checked my notes that I made during the process and I did run this. I received the following back.

```
dcgmi discovery -l
Error: unable to establish a connection to the specified host: localhost
Error: Unable to connect to host engine. Host engine connection invalid/disconnected.
```

This happened on nodes configured with both MIG and passthrough. As I say it was physical nodes with the GPUs installed on which OpenStack VMs were deployed and then K8S deployed across said VMs so I'm not sure if the chain causes an issue along the line somewhere. I'd have expected passthrough to work though at the very least.

I'm hoping to have access to NVIDIA GPUs soon so I can continue this if/when that happens however if you need to close this and have me reopen this/create a new issue I'm happy to do so. I was hoping to get to the bottom of this before the new role began 😄
