### ISSUE TITLE
what is DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL ?  What's the difference with TX_BYTES and RX_BYTES?

### ISSUE THREAD

**Issue by PrometheusComing** [NVIDIA/dcgm-exporter#195]
Hello, I want to know whether the metric DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL is related to the metric DCGM_FI_PROF_NVLINK_TX_BYTES&DCGM_FI_PROF_NVLINK_RX_BYTES . I'm thinking that BANDWIDTH_TOTAL is about the sum of TX_BYTES and RX_BYTES, is it right?. Is the unit of DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL B/S? I look forward to someone who can help me answer my questions. Thank you very much.

DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL,            counter, Total number of NVLink bandwidth counters for all lanes.
DCGM_FI_PROF_NVLINK_TX_BYTES, gauge, The number of bytes of active NvLink tx (transmit) data including both header and payload.
DCGM_FI_PROF_NVLINK_RX_BYTES, gauge, The number of bytes of active NvLink rx (read) data including both header and payload.

**Comment by PrometheusComing** [comment]
Thank you for reply. @glowkey

**Comment by vissible** [comment]
B/s or B?
