### ISSUE TITLE
How to export a specified filed ？

### ISSUE THREAD

**Issue by jxh314** [NVIDIA/dcgm-exporter#210]
Hello！
By editing the file` etc/default-counters.csv`, I add some fileds  but it can't work with the prompt below:

```
> INFO[0000] Starting dcgm-exporter                       
> INFO[0000] DCGM successfully initialized!               
> INFO[0000] Not collecting DCP metrics: This request is serviced by a module of DCGM that is not currently loaded 
> INFO[0000] No configmap data specified, falling back to metric file /my-counters.csv 
> FATA[0000] Could not find DCGM field DCGM_FI_DEV_BAR1_USED 
```
I can obtain the information of the filed DCGM_FI_DEV_BAR1_USED with the command `dcgmi dmon -e 92` but here it can't work. May I ask why  and  does the complete list of counters that  can be found on the DCGM API reference manual: [https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html) can be collected? Or is there any other configuration to be done? Thanks a lot!

**Comment by glowkey** [comment]
Can you paste the line you added to the file? This field should work. I was not able to reproduce this problem using version 3.3.0-3.2.0-ubuntu22.04 and driver version 535:

```
$ curl -s localhost:9400/metrics | grep BAR
# HELP DCGM_FI_DEV_BAR1_USED amount used
# TYPE DCGM_FI_DEV_BAR1_USED gauge
DCGM_FI_DEV_BAR1_USED{gpu="0",UUID="...",device="nvidia0",modelName="...",Hostname="52e651a75ccb",DCGM_FI_DRIVER_VERSION="535.58"} 2
```

**Comment by jxh314** [comment]
Sure, here it is. @glowkey 

> #BAR1
> DCGM_FI_DEV_BAR1_USED	,gauge	,MB	表示已使用的BAR1。
> DCGM_FI_DEV_BAR1_FREE	,gauge	,MB	表示剩余的BAR1。
