### ISSUE TITLE
Running DCGM Exporter on RHEL 9 w/ podman returns  Error: Failed to initialize NVML

### ISSUE THREAD

**Issue by pwharned** [NVIDIA/dcgm-exporter#211]
`sudo podman run --rm --gpus all --cap-add SYS_ADMIN --security-opt seccomp=unconfined -p 9400:9400 nvcr.io/nvidia/k8s/dcgm-exporter:latest`

I am trying to run the nvidia exporter locally using podman on Rhe.

Do you suport/ is there a known issue with using podman? 
Do  you support/is there a known issue with rhel9?
Special SeLinux modules needed?

Is there a way to get more verbose logs to do some debugging?

![image](https://github.com/NVIDIA/dcgm-exporter/assets/52669420/3cc0c52d-b639-4a82-9438-cffe206686f9)
![image](https://github.com/NVIDIA/dcgm-exporter/assets/52669420/c185e2e2-fea1-420e-aecd-e124e8a68b1d)

**Comment by nikkon-dev** [comment]
@pwharned,

Can you run `nvidia-smi` inside the pod (not the host)? If not, that's most likely the nvidia-runtime does not work properly in your podman.

**Comment by pwharned** [comment]
Actually following the instructions here lead me to a more useful error: https://github.com/Gaussianer/Podman---Run-Rootless-GPU-Container

**Comment by pwharned** [comment]
![image](https://github.com/NVIDIA/dcgm-exporter/assets/52669420/0a2fbd74-2931-48a3-86d1-3bcf689f5cf9)

**Comment by pwharned** [comment]
attempting to run nvidia-smi gives the same error (doesnt look like its actually running the command in the pod tbh)

![image](https://github.com/NVIDIA/dcgm-exporter/assets/52669420/62d6809f-b1de-40fc-ae33-761cf57b52d1)

**Comment by nikkon-dev** [comment]
@pwharned,

From the [instructions](https://github.com/Gaussianer/Podman---Run-Rootless-GPU-Container)
> If the test passes, the drivers, hooks and the container runtime are functioning correctly

Unfortunately, the error you see means that the nvidia-container-toolkit does not work/installed correctly. 

I did not mean to run nvidia-smi inside the dcgm-exporter container. Any container, even bare Ubuntu, should have the nvidia-smi if the container toolkit works appropriately (under the hood, the nvidia-smi, nvidia-ml.so and other required libraries and driver parts are mounted inside any container that runs with the `--gpu` argument).

Unfortunately, I cannot provide more guidance on how the nvidia-container-toolkit should be installed/configured with rootless podman - that's outside of my field of expertise.

**Comment by pwharned** [comment]
@nikkon-dev 

I am actually able to run the dcgm-exporter by building from source, its only the container that doesnt work. I've also verified that the toolkits are correctly installed which you can see from the screenshot, I generated a sample load on my local dcgm etc. I will try to build my own container to identify what is causing this issue and see If I can't fix it. 

![image](https://github.com/NVIDIA/dcgm-exporter/assets/52669420/d96c1e6c-cc01-4fba-919a-32b152388785)
