### ISSUE TITLE
(Question) Value for `DCGM_FI_DEV_GPU_UTIL` metric for MIG instances

### ISSUE THREAD

**Issue by sia-hk** [NVIDIA/dcgm-exporter#216]
Hi all,

I think this might be a duplicated question, but I can't find any issues or references related to this:

The problem we encountered is that all the metic values for `DCGM_FI_DEV_GPU_UTIL` are set to 0 for MIG instances. So,

1. Is this normal behavior?
2. If this is normal, is there any alternative way to get GPU utilization?
3. When this feature will be developed?

Plus, here is our kubernetes cluster information:

Kubernetes version: `1.24.9`
DCGM exporter image: `nvcr.io/nvidia/k8s/dcgm-exporter:3.3.0-3.2.0-ubuntu22.04`
GPU: `NVIDIA A100 SXM 80GB`

Thx

**Comment by nvvfedorov** [comment]
1) Yes, it is normal 

2) DCGM_FI_PROF_GR_ENGINE_ACTIVE 

3) Today, there are no plans to support DCGM_FI_DEV_GPU_UTIL for MIG instances.

**Comment by sia-hk** [comment]
Thanks for the quick reply. I'll close this issue as completed.
