### ISSUE TITLE
Docker Imagers newer than dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 do not appear to support `"/bin/sh", "-c"`

### ISSUE THREAD

**Issue by hassanbabaie** [NVIDIA/dcgm-exporter#218]
We're currently using the

```
      containers:
      - image: nvidia_dcgm_exporter_image
        command: ["/bin/sh", "-c"]
        args:
          - echo "setting up csv";
            touch /etc/dcgm-exporter/dcp-metrics-bolt.csv;
            echo "DCGM_FI_DEV_GPU_UTIL,gauge,GPU utilization (in %)." >> /etc/dcgm-exporter/dcp-metrics-bolt.csv;
```

However it looks like the images newer than `dcgm-exporter:3.1.7-3.1.4-ubuntu20.04` do not support`"/bin/sh", "-c"`

Is there a way round this as it currently works very well for us to keep the config in the deployment

**Comment by nvvfedorov** [comment]
When you say:  "works very well for us to keep the config in the deployment" - what do you mean? Can you tell us a full usage scenario?

**Comment by hassanbabaie** [comment]
@nvvfedorov yes it just makes updates easier as when we update the config in the deployment the deployment is updates and refreshed. If we use a configmap then we have to perform to steps

**Comment by nikkon-dev** [comment]
I do not see any difference between those those versions. I could only see that older images have symlink `/bin/sh -> /usr/bin/dash` and newer `/bin/sh -> /usr/bin/bash`.
In the local run, newer and older images behave in a similar way `docker run -t --entrypoint /bin/sh <image> -c 'echo hello'`.

Also, try to change 
```
command: ["/bin/sh"]
args: 
   - -c
     touch "..."
      ....
```

**Comment by hassanbabaie** [comment]
Sorry for the very late reply,

This was user error on my part, I had switched to an M2 MacBook and so when running the `docker pull nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.4.0-ubuntu22.04`

To store locally it was default to the arm image,

I fixed it by pulling with the platform flag:

`docker pull nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.4.0-ubuntu22.04 --platform linux/amd64   `
