### ISSUE TITLE
Helm Charts page returning 404

### ISSUE THREAD

**Issue by tynewydd-docusign** [NVIDIA/dcgm-exporter#221]
Hey the readme and other pages nearby suggest getting the helm charts from https://nvidia.github.io/gpu-monitoring-tools/helm-charts

But this returns a 404. 

Any chance of getting it going again, or providing an alternate? 

Regards,
Adam

**Comment by nikkon-dev** [comment]
@tynewydd-docusign 

[Docs](https://github.com/NVIDIA/dcgm-exporter/blob/gh-pages/index.md)

```
helm repo add gpu-helm-charts \
    https://nvidia.github.io/dcgm-exporter/helm-charts
```

**Comment by tynewydd-docusign** [comment]
That is interesting but also gives a 404.

**Comment by arjungangisetty** [comment]
@nikkon-dev We have tried below URL but it is giving 404. Could you help fix it ?
https://nvidia.github.io/dcgm-exporter/helm-charts
<img width="1245" alt="Screenshot 2023-12-18 at 12 32 38 PM" src="https://github.com/NVIDIA/dcgm-exporter/assets/58575610/240f0d40-fabd-40d1-970e-6fbab521c712">
cc @tynewydd-docusign

**Comment by glowkey** [comment]
Is the command `helm repo add gpu-helm-charts https://nvidia.github.io/dcgm-exporter/helm-charts` working for you? 

Note that the helm charts are located here: https://github.com/NVIDIA/dcgm-exporter/tree/gh-pages/helm-charts. They are not meant to be a web page in this case.

**Comment by nvvfedorov** [comment]
> @nikkon-dev We have tried below URL but it is giving 404. Could you help fix it ? https://nvidia.github.io/dcgm-exporter/helm-charts <img alt="Screenshot 2023-12-18 at 12 32 38 PM" width="1245" src="https://private-user-images.githubusercontent.com/58575610/291401979-240f0d40-fabd-40d1-970e-6fbab521c712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzIzNTUsIm5iZiI6MTcwMjkzMjA1NSwicGF0aCI6Ii81ODU3NTYxMC8yOTE0MDE5NzktMjQwZjBkNDAtZmFiZC00MGQxLTk3MGUtNmZiYWI1MjFjNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIwNDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNmVlZGZiOGNjZTliMWZlNjRlOTc4OWJlMzJkMDYzOWQwMzc1NTY0ZGM5OWI4NTM0ZTgwMjE5OWZjMjM2MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaYX64B6qGzn_yJ2araCYp-TwivjX63Ph3mEy9tKiqs"> cc @tynewydd-docusign

Github doesn't allow the list of directory content. When you run, for example, the command below, you can download the chart: 
```
wget https://nvidia.github.io/dcgm-exporter/helm-charts/dcgm-exporter-3.2.0.tgz
```

You can use the following command to list the repository content:

```
helm search repo -l
```
