### ISSUE TITLE
Why does the collection of GPU utilization experience jitter by NVML library ?

### ISSUE THREAD

**Issue by xuchenhui-5** [NVIDIA/dcgm-exporter#227]
Hi,
I directly conducted demo testing based on the NVML library provided by NVIDIA, using a [single thread] to collect GPU utilization and calling the NVML DeviceGetUtilitationRates API. Most of the time, the time consumption was very ideal, but there were occasional severe jitters. The rt field in the following figure shows the time consumption (ms) of this API. Can you help explain the reason? 

Thank you

![screenshots](https://github.com/NVIDIA/dcgm-exporter/assets/10278702/dd496d50-4a3a-44a0-82b8-5443c04c85bd)

**Comment by nvvfedorov** [comment]
"What do you mean by 'the library'?"

**Comment by xuchenhui-5** [comment]
> "What do you mean by 'the library'?"

In terms of GPU data collection, dcgm exporter indirectly relies on the NVML library in the following order: DCGM exporter ->DCGM ->NVVS ->NVML, while I directly collect GPU data based on the NVML library and want to test the performance of the NVML library directly.

**Comment by vfedoroff** [comment]
In this case, it is better to post the question in the nvml library repository.
