### ISSUE TITLE
Support for Grace CPU overflows DCGM_GROUP_MAX_ENTITIES

### ISSUE THREAD

**Issue by bsteinb** [NVIDIA/dcgm-exporter#231]
The support for gathering metrics from Grace CPUs introduced in #225 currently aborts the program when run on Grace CPUs. `CreateCoreGroupsFromSystemInfo` creates a DCGM group per CPU and tries to add all the cores of a CPU to that group as entities. However, Grace has 72 CPU cores while DCGM groups can only contain a maximum of 64 entities (https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-enums.html#c.DCGM_GROUP_MAX_ENTITIES). This leads to `dcgm.AddEntityToGroup` returning an error, which is passed up the chain `CreateCoreGroupsFromSystemInfo -> SetupDcgmFieldsWatch -> NewDCGMCollector` which aborts via `logrus.Fatal("Failed to watch metrics: ", err)`.

**Comment by glowkey** [comment]
We appreciate this report. This will be addressed in the next official release.
