### ISSUE TITLE
how to build it for arm64 under x86?

### ISSUE THREAD

**Issue by zhucan** [NVIDIA/dcgm-exporter#232]
```
[root@rook-node01 dcgm-exporter]# CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc CGO_LDFLAGS="-static"  go build
# runtime/cgo
_cgo_export.c:3:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.****
```

**Comment by nikkon-dev** [comment]
The error message you're seeing suggests that the GCC headers for the target platform are not correctly installed on your system. Cross-compilation with CGO in Go is not ideal.
I could recommend this article as an alternative way to make cross-builds: https://dev.to/kristoff/zig-makes-go-cross-compilation-just-work-29ho
