### ISSUE TITLE
ubuntu16 support dcgm-exporter?

### ISSUE THREAD

**Issue by wangqiangJN** [NVIDIA/dcgm-exporter#233]
I want to konw ubuntu16 support dcgm-exporter or not，there has frame to show that?

**Comment by zhucan** [comment]
@wangqiangJN https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/getting-started.html from this doc, I think not support.

**Comment by nikkon-dev** [comment]
The dcgm-exporter cannot be used in Ubuntu 16.04 since the current version of DCGM does not support it. This is because the client library libdcgm.so depends on a newer GLIBc version which is not provided in Ubuntu 16.04.
