### ISSUE TITLE
GPU Utilization Panel displays multiple GPU data when the node has only 1 GPU

### ISSUE THREAD

**Issue by Levi080513** [NVIDIA/dcgm-exporter#237]
When I use the default provided [dashboard](https://github.com/NVIDIA/dcgm-exporter/blob/main/grafana/dcgm-exporter-dashboard.json) to view GPU monitoring information, I find that once I rebuild the Pod that using the GPU, GPU Utilization Panel displays multiple GPU data when the node has only 1 GPU.

<img width="700" alt="image" src="https://github.com/NVIDIA/dcgm-exporter/assets/114376205/ebf4bd69-158f-4abe-bc9b-c6b98460695f">

**Comment by dbblackdiamond** [comment]
I am seeing the exact same thing:
![Screenshot 2024-02-01 171623](https://github.com/NVIDIA/dcgm-exporter/assets/11542603/ce91a4dc-e27c-4916-a7ae-829afdfdeea5)

We are running gpu-operator v23.9.1 on kubernetes v1.28.2 on ubuntu 22.04.3. All our GPUs are running driver v535.129.03.

I have dug into the prometheus metrics and the only thing I can see is that for the same GPU, some scrapes include `exported_pod` and `exported_namespace` fields when others don't. I think prometheus is treating those as different series.

Thoughts?

**Comment by Levi080513** [comment]
I think we can avoid being recognized as different GPUs through prometheus's aggregation function, eg `sum(DCGM_FI_DEV_GPU_UTIL) by (modelName,instance,gpu)`

**Comment by nikkon-dev** [comment]
Could you check the raw Prometheus output and compare labels on that metric?

**Comment by Levi080513** [comment]
> Could you check the raw Prometheus output and compare labels on that metric?

```
{DCGM_FI_DRIVER_VERSION="525.105.17", Hostname="nvidia-dcgm-exporter-j2dld", UUID="GPU-a5ee8b12-c194-11ee-b88d-feea9bbda686", __name__="DCGM_FI_DEV_GPU_UTIL", container="nvidia-dcgm-exporter", device="nvidia0", endpoint="gpu-metrics", exported_container="main", exported_namespace="default", exported_pod="gpu-burn-7bf79f8dff-m7gpm", gpu="0", instance="172.16.130.148:9400", job="nvidia-dcgm-exporter", modelName="GRID V100-4C", namespace="sks-system-nvidia-gpu", node="hw-sks-test-vgpu-workergroup1-p975p", pod="nvidia-dcgm-exporter-j2dld", service="nvidia-dcgm-exporter"}
{DCGM_FI_DRIVER_VERSION="525.105.17", Hostname="nvidia-dcgm-exporter-j2dld", UUID="GPU-a5ee8b12-c194-11ee-b88d-feea9bbda686", __name__="DCGM_FI_DEV_GPU_UTIL", container="nvidia-dcgm-exporter", device="nvidia0", endpoint="gpu-metrics", exported_container="main", exported_namespace="default", exported_pod="gpu-burn-7bf79f8dff-zlt4d", gpu="0", instance="172.16.130.148:9400", job="nvidia-dcgm-exporter", modelName="GRID V100-4C", namespace="sks-system-nvidia-gpu", node="hw-sks-test-vgpu-workergroup1-p975p", pod="nvidia-dcgm-exporter-j2dld", service="nvidia-dcgm-exporter"}
```
The value of the label `exported_pod` is different.

**Comment by dbblackdiamond** [comment]
This is what I am seeing for the same metric for the same GPU. These 2 lines results in different graphs in Grafana:
```
DCGM_FI_DEV_GPU_UTIL{DCGM_FI_DRIVER_VERSION="535.129.03", Hostname="worker54.ava.ai.lab", UUID="GPU-09ac954c-d587-43f7-78d8-274d772a59a5", container="nvidia-dcgm-exporter", device="nvidia3", endpoint="gpu-metrics", exported_container="service", exported_namespace="pryon", exported_pod="int-delphiranking-7465f95bbd-4gn85", gpu="3", instance="10.10.4.20:9400", job="nvidia-dcgm-exporter", modelName="NVIDIA L4", namespace="gpu-operator", pod="nvidia-dcgm-exporter-qz4kf", service="nvidia-dcgm-exporter"}
DCGM_FI_DEV_GPU_UTIL{DCGM_FI_DRIVER_VERSION="535.129.03", Hostname="worker54.ava.ai.lab", UUID="GPU-09ac954c-d587-43f7-78d8-274d772a59a5", container="nvidia-dcgm-exporter", device="nvidia3", endpoint="gpu-metrics", gpu="3", instance="10.10.4.20:9400", job="nvidia-dcgm-exporter", modelName="NVIDIA L4", namespace="gpu-operator", pod="nvidia-dcgm-exporter-qz4kf", service="nvidia-dcgm-exporter"}
```
The only difference between the 2 is that one includes `exported_*` tags but the others don't.

**Comment by nvvfedorov** [comment]
The "exported_*" tags result from the Prometheus configuration. See: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config 

```
# If honor_labels is set to "false", label conflicts are resolved by renaming
# conflicting labels in the scraped data to "exported_<original-label>" (for
# example "exported_instance", "exported_job") and then attaching server-side
# labels.
```

As I see from the provided by @dbblackdiamond sample, I see, that metrics were collected from two different pods:
`exported_pod="int-delphiranking-7465f95bbd-4gn85"` and `exported_pod="int-delphianswering-888c75798-t6qf9"`, both pods used the same `gpu=3`. That is expected because the pod was recreated.

**Comment by nvvfedorov** [comment]
@dbblackdiamond , @Levi080513, According to the Prometheus Data Model (https://prometheus.io/docs/concepts/data_model/):

Prometheus stores all data as time series. Every time series is uniquely identified by its metric name and optional key-value pairs called labels. The change of any label's value, including adding or removing labels, will create a new time series.

When a pod uses the GPU, the DCGM exporter adds information about which POD uses the GPU to the metric labels. This creates a new time series.

You can combine time series into one by using the following grafana query:

```
max by(instance, gpu) (DCGM_FI_DEV_GPU_UTIL{instance!~"$instance", gpu!~"$gpu"})
```

Also, you can configure Prometheus to perform relabeling. See: https://training.promlabs.com/training/relabeling/introduction-to-relabeling/relabeling-overview.
