### ISSUE TITLE
CPU power and temperature metrics should create a single time line per sensor

### ISSUE THREAD

**Issue by bsteinb** [NVIDIA/dcgm-exporter#243]
CPU power and temperature are currently reported per CPU core. However, Grace has sensors for temperature and power at the module / socket level, so a single time line would suffice where currently there are 72.

**Comment by rnertney** [comment]
Thanks for your suggestion! We have taken this into consideration :)

**Comment by npes87184** [comment]
Hi @bsteinb ,

Currently, CPU power and temperature are reported per CPU socket. I ran the dcgm exporter in the Grace CPU environment, it only produces one temperature and power metric for a CPU.

```
# HELP DCGM_FI_DEV_CPU_TEMP_CURRENT CPU temp
# TYPE DCGM_FI_DEV_CPU_TEMP_CURRENT gauge
DCGM_FI_DEV_CPU_TEMP_CURRENT{cpu="0"} 39.500000
DCGM_FI_DEV_CPU_TEMP_CURRENT{cpu="1"} 39.500000
# HELP DCGM_FI_DEV_CPU_POWER_UTIL_CURRENT CPU Power
# TYPE DCGM_FI_DEV_CPU_POWER_UTIL_CURRENT gauge
DCGM_FI_DEV_CPU_POWER_UTIL_CURRENT{cpu="0"} 31.427000
DCGM_FI_DEV_CPU_POWER_UTIL_CURRENT{cpu="1"} 31.427000
```

Could you provide more information about the timeline? How did you reproduce it? What is the version of DCGM and dcgm-exporter? Could you also provide the details of your hardware?

Thank you very much.

Regards,
Yu-Chen Lin
