### ISSUE TITLE
I can't add an annotation

### ISSUE THREAD

**Issue by edeno1** [NVIDIA/dcgm-exporter#249]
Hello, I am trying to add an annotation of:
```
   annotations:
     prometheus.io/port: "metrics"
     prometheus.io/scrape: "true"
```
But everything I try to do doesn't work
This is how I raise my helm

```
resource "helm_release" "dcgm" {
  name      = "dcgm-exporter"
  repository = "https://nvidia.github.io/dcgm-exporter/helm-charts"
  chart     = "dcgm-exporter"
  namespace = monitoring
  values = [jsonencode({
    service = {
      annotations ={
        "prometheus.io/port": "metrics"
        "prometheus.io/scrape": "true"
      }
    }
  })]
}
```

this is the logs in pods :
```
kubectl logs -f dcgm-exporter -n monitoring
time="2024-02-04T15:02:01Z" level=info msg="Starting dcgm-exporter"
Error: Failed to initialize NVML
time="2024-02-04T15:02:01Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"

```

**Comment by nvvfedorov** [comment]
@edeno1 , Thank you for reporting the issue. Can you explain what exactly doesn't work?

Also, please provide information about DCGM exporter/DCGM versions and information about hardware. Also, please check the following log file: /var/log/nv-hostengine.log for errors.

**Comment by edeno1** [comment]
Hi @nvvfedorov 

- I am trying to install using helm dcgm exporter (k8s)
- only of node in gpu whit ami (Bottlerocket)
- But every time I try to install the dcgm pods fall and I see the following log ```
: kubectl logs -f dcgm-exporter -n monitoring
time="2024-02-04T15:02:01Z" level=info msg="Starting dcgm-exporter"
Error: Failed to initialize NVML
time="2024-02-04T15:02:01Z" level=fatal msg="Error starting nv-hostengine: DCGM initialization error"
```
![image](https://github.com/NVIDIA/dcgm-exporter/assets/105434541/ab9e9b27-20b9-4ab5-a9ba-b3804ae8bc76)

**Comment by nvvfedorov** [comment]
@edeno1 , Please run `ps -ef` and share the command line with parameters for the dcgm-exporter.
