### ISSUE TITLE
Compiling with Go 1.18.1

### ISSUE THREAD

**Issue by michaelfuckner** [NVIDIA/dcgm-exporter#255]
I try to compile this software on DGX H100 with DGX OS 6.1 providing go 1.18.1

Is it correct, I now need newer Version of go to compile?

git clone https://github.com/NVIDIA/dcgm-exporter && cd dcgm-exporter/ && make binary
cd cmd/dcgm-exporter; go build -ldflags "-X main.BuildVersion=3.3.3-3.3.1"
../../pkg/dcgmexporter/xid_collector.go:22:2: package maps is not in GOROOT (/usr/lib/go-1.18/src/maps)
../../pkg/dcgmexporter/system_info.go:22:2: package slices is not in GOROOT (/usr/lib/go-1.18/src/slices)
make: *** [Makefile:36: binary] Error 1
admin2@nfr-dgx:~/dcgm-exporter$ go version
go version go1.18.1 linux/amd64

**Comment by nvvfedorov** [comment]
This is correct. Now you need to use at least GO 1.21

**Comment by michaelfuckner** [comment]
fix applied
