### ISSUE TITLE
Attributing GPU power among MIG instances.

### ISSUE THREAD

**Issue by fali007** [NVIDIA/dcgm-exporter#257]
We were doing some experiments using MIG instances and how we can attribute the power consumed by GPU among the MIG instances instead of reporting whole GPU power as MIG power irrespective of the compute capability per instance. Will it be possible for us to add this to DCGM exporter?

**Comment by fali007** [comment]
Can I add this to dcgm_exporter?

**Comment by vfedoroff** [comment]
Yes, we will review and test the PR.

**Comment by nvvfedorov** [comment]
Yes, you can. We accept PRs after review and testing. Please read contribution guidelines: https://github.com/NVIDIA/dcgm-exporter/blob/main/CONTRIBUTING.md

**Comment by nvvfedorov** [comment]
@fali007, If new metrics will be calculated on the dcgm-exporter side, please use the "DCGM_FI_EXP_" prefix for new metrics. Also, follow the pattern for new metrics: DCGM_FI_EXP_CLOCK_THROTTLE_REASONS_COUNT and DCGM_EXP_XID_ERRORS_COUNT.

I mean, new metrics produced by the dcgm-exporter must be implemented as a collector (example: https://github.com/NVIDIA/dcgm-exporter/blob/0e6432774751b6efcb77f9d85c80eaedae25b054/pkg/dcgmexporter/clocks_throttle_reasons_collector.go) which implements the Collector interface.

**Comment by fali007** [comment]
Thank you.

**Comment by frittentheke** [comment]
@nvvfedorov currently the exporter does provide power metrics for all MIG subdevices (`GPU_I_ID`), so e.g. `DCGM_FI_DEV_POWER_USAGE`. I consider this a bug, provided that this is NOT the individual power draw.

Would you reopen this one a a bug, or should a raise a new issue?
