### ISSUE TITLE
Runing DCGM on Red Hat

### ISSUE THREAD

**Issue by nicolaspasqual** [NVIDIA/dcgm-exporter#267]
Hi everyone,

I would like to know if there is a way to run the dcgm-exporter on Red Hat 8.8 using podman.
I tried to use the exporter and it is not running.

**Comment by glowkey** [comment]
Please include logs, versions,  and any other relevant information.

**Comment by nicolaspasqual** [comment]
I build the binary locally to work the exporter instead of using the container image.
