### ISSUE TITLE
Get Pod and Namespace based GPU usage metrics

### ISSUE THREAD

**Issue by PratapSingh13** [NVIDIA/dcgm-exporter#277]
Hi,
Just like to know that how we can get GPU metrics for Pods and Namespace based usage. There can be a challenge to get know about a GPU based application we are running in an environment and wants to know like what GPU values our application pod is using.
I found that there are no labels in DCGM based metrics in Grafana. We have labels only like below
`DCGM_FI_DEV_GPU_UTIL{DCGM_FI_DRIVER_VERSION="535.154.05", Hostname="node-1", UUID="GPU-16355474-d5ef-9c9f-3367-6ff0eaa0e4a7", device="nvidia2", gpu="2", instance="nvidia-dcgm-exporter.gpu-operator:9400", job="dcgm-nvidia-gpu-operator", modelName="Quadro RTX 6000"}
`

**Comment by nvvfedorov** [comment]
When a GPU workload is running on the cluster, the dcgm-exporter produces labels with pod, container, and namespace.
