### ISSUE TITLE
 Error creating DCGM fields group: Duplicate Key passed to function

### ISSUE THREAD

**Issue by SSSherg** [NVIDIA/dcgm-exporter#29]
when i do this:
dcgm-exporter -f  default-counters.csv
show:
FATA[0001] Error creating DCGM fields group: Duplicate Key passed to function

I wonder why？please!

**Comment by SSSherg** [comment]
i want to Changing Metrics...

**Comment by nikkon-dev** [comment]
Hey, 

It would be very helpful if you could provide us with the nv-hostengine debug logs.
To enable them, you need to re-run the nv-hostengine with the following flags: `nv-hostengine -f logfile.log --log-level debug`

WBR,
Nik

**Comment by SSSherg** [comment]
I circumvented this problem by mounting CVS files
