### ISSUE TITLE
How to get SM Occupancy in real-time except dcgm in RTX Series?

### ISSUE THREAD

**Issue by taekyounghan** [NVIDIA/dcgm-exporter#294]
Hello, I'm new to dcgm..

I'm trying to get profiling value in real-time and used dcgm.

But my GPU (RTX3090) doesn't support dcgm profiling. (https://github.com/NVIDIA/dcgm-exporter/issues/152#issuecomment-1507618717)

1) Is there any updating plan that RTX series can profile metrics with dcgm? all it will not forever?

2) Is there any workaround to get that value in real-time?

Nsight also gave me that value but it is non-real-time data..

Any comment will be super helpful.

Thanks
Taekyoung

**Comment by glowkey** [comment]
The GeForce cards do not support profiling. It is a hardware limitation.
