### ISSUE TITLE
GPU metrics for LLM autoscaling

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/dcgm-exporter#301]
### Ask your question

We are running LLM applications and plan to enable HPA for our application.

The tricky thing is GPU utilization becomes very high if there's even single request. In that case, even I use SM active, SM active for new created pod will be close to my setting (let's say 60%), that means it will keep scaling up. We know that SM active can not represent the real busyness, what's the best practice for such applications?

I tried to use SM occupancy but seems it won't go higher even there're concurrent requests.

**Comment by nvvfedorov** [comment]
@Jeffwan , I think you can ask the same question here: https://github.com/NVIDIA/DCGM/issues

**Comment by Jeffwan** [comment]
@nvvfedorov Hi, Thanks for heads up. I may left comment in some threads? https://github.com/NVIDIA/DCGM/issues/created_by/Jeffwan I do search the issues and can not find anything under me. Do you think this is the right place to discuss this issue? If not, I can move to the right repo.

**Comment by Jeffwan** [comment]
@nvvfedorov I carelessly read the message and misunderstood your statement. Yeah, sounds good and I will move my question to DCGM repo. Thanks!
