### ISSUE TITLE
Support collect detail error message with the xid

### ISSUE THREAD

**Issue by zhucan** [NVIDIA/dcgm-exporter#308]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### Please provide a clear description of the problem this feature solves

We need to know the detail error messages with the xid, like this: https://docs.nvidia.com/deploy/xid-errors/#topic_4

### Feature Description

I want to collect the detail error message with the xid error.

### Describe your ideal solution

collect the xid error code and error message.

**Comment by jz543fm** [comment]
I would say this enhancement could be closed, since the detail error messages are actually available in release of dcgm-exporter: [3.3.6-3.4.2](https://github.com/NVIDIA/dcgm-exporter/releases/tag/3.3.6-3.4.2) where you have err_msg label for XID errors for metric DCGM_FI_DEV_XID_ERRORS
