### ISSUE TITLE
dcgm-exporter high cpu usage

### ISSUE THREAD

**Issue by mbacchi** [NVIDIA/dcgm-exporter#311]
### What is the version?

3.3.5-3.4.1

### What happened?

When running the dcgm-exporter on Amazon Linux, we see very high sustained CPU usage. This is seen when there are no other resource intensive processes running on the system. There is no major difference in the CPU utilization whether there are GPU intensive processes running on the system or not (meaning CPU doesn't increase or decrease much for this process when GPU intensive processes are executing.)

```
top - 20:36:36 up 1 day,  6:51,  0 users,  load average: 1.37, 0.97, 0.45
Tasks: 230 total,   1 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.6 us,  6.3 sy,  0.0 ni, 92.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65135640 total, 57922344 free,  2483932 used,  4729364 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 61930124 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17657 root      20   0 3441212 253788  38028 S 131.2  0.4   7:03.08 dcgm-exporter
```

### What did you expect to happen?

CPU usage shouldn't be so high.

### What is the GPU model?

```
nvidia-smi
Tue Apr  9 20:40:02 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:1E.0 Off |                    0 |
| N/A   40C    P0             38W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### What is the environment?

This is running on an Amazon Linux 2 EC2 instance (instance type is `g4dn.4xlarge`):
```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
```

### How did you deploy the dcgm-exporter and what is the configuration?

We are using the NVIDIA docker image:

```
docker run --pid=host --privileged -e DCGM_EXPORTER_INTERVAL=3 --gpus all -d -v /proc:/proc -p 9400:9400 --name dcgm-exporter nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.4.1-ubi9
```

### Anything else we need to know?

There was a similar [issue](https://github.com/NVIDIA/gpu-monitoring-tools/issues/133) opened in the gpu-monitoring repository about this problem in 2020, but it was never resolved before that repository was archived.

**Comment by nvvfedorov** [comment]
@mbacchi , Try to increase the `DCGM_EXPORTER_INTERVAL` value. A DCGM_EXPORTER_INTERVAL =3 value means that DCMG reads GPU metrics every three milliseconds!  The default value, for example, is 30000 ms.

**Comment by mbacchi** [comment]
Oh wow, thanks for the very quick response @nvvfedorov. I was using this command based on the Datadog suggested command to use to launch dcgm-exporter [here](https://github.com/DataDog/integrations-core/blob/master/dcgm/README.md#installation). They said:

```
Run the Docker container using the following command:

sudo docker run --pid=host --privileged -e DCGM_EXPORTER_INTERVAL=3 --gpus all -d -v /proc:/proc -v $PWD/default-counters.csv:/etc/dcgm-exporter/default-counters.csv -p 9400:9400 --name dcgm-exporter nvcr.io/nvidia/k8s/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04
```

I also had to skip using the counters they recommend because it would cause the dcgm-exporter process to crash. So what you're saying now about the interval is a second problem with their suggested command.

**Comment by mbacchi** [comment]
And your recommendation does in fact improve the situation immensely. Now we see with this command:

```
docker run --pid=host --privileged -e DCGM_EXPORTER_INTERVAL=30000 --gpus all -d -v /proc:/proc -p 9400:9400 --name dcgm-exporter nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.4.1-ubi9

top
...
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
...
21432 root      20   0 2681360 178876  37616 S   1.0  0.3   0:00.34 dcgm-exporter

ps -ef | grep dcgm
root     21432 21393  0 20:55 ?        00:00:00 /usr/bin/dcgm-exporter
```

It usually doesn't break 1% CPU now.

Thanks for your assistance. It looks like this is resolved.
