### ISSUE TITLE
Metrics around capturing gpu FLOPS

### ISSUE THREAD

**Issue by krishh85** [NVIDIA/dcgm-exporter#320]
### Ask your question

The metric "DCGM_FI_PROF_PIPE_FP64_ACTIVE" is defined as the "Ratio of cycles the fp32 pipe is active". I suppose the units is tie here. How do we equate this to FLOPS count. For example in A100  as per the [article](https://developer.nvidia.com/blog/nvidia-ampere-architecture-in-depth) seems to have max of 19.5TFLOPS (count).
1. Is it reasonably correct to convert the  "DCGM_FI_PROF_PIPE_FP64_ACTIVE" % in absolute FLOP count? i.e 50% value of 
 DCGM_FI_PROF_PIPE_FP64_ACTIVE  == 0.5 * 19.5 = 9.75 TFLOPS?
2. There also seems to be different pipes for 16/32 bit operations(DCGM_FI_PROF_PIPE_FP16_ACTIVE/DCGM_FI_PROF_PIPE_FP32_ACTIVE) , how are these related to "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE" metric?

What would be the ideal way to get the FLOPs (count) currently being worked by the GPU?

**Comment by glowkey** [comment]
Can you repost your question to the DCGM repo as that is more appropriate for details around individual metrics: https://github.com/NVIDIA/dcgm/issues

**Comment by krishh85** [comment]
moving this to dcgm repo
