### ISSUE TITLE
Executing dcgmi diag -r 3 in dcgm-exporter, the prompt shows "nvvs binary was not found"

### ISSUE THREAD

**Issue by 287400117** [NVIDIA/dcgm-exporter#324]
### What is the version?

3.3.5-3.4.1

### What happened?

* Executing `dcgmi diag -r 3` in dcgm-exporter, the prompt shows：
> error when executing the diagnostic: the nvvs binary was not found in the specified location; please install it to /usr/share/nvidia-validation-suite/ or set environment variable nvvs_bin_path to the directory containing nvvs. if you set nvvs_bin_path, please restart the dcgm service (nv-hostengine) if it is active.
![企业微信截图_f1768d40-9c20-4559-97b6-9c10a967b0f7](https://github.com/NVIDIA/dcgm-exporter/assets/4199281/e1fcd7ba-ca9b-4675-8443-7415308c32aa)

Final troubleshooting revealed that there is a section of code in the Dockerfile that deletes the `/usr/share/nvidia-validation-suite` directory after installing datacenter-gpu-manager.
![企业微信截图_4d7f6acb-ca8f-4c06-b585-ea898d117e15](https://github.com/NVIDIA/dcgm-exporter/assets/4199281/51b52f49-3e87-4df1-9a7d-ad3879f08c11)

### What did you expect to happen?

The command `dcgmi diag -r 3` can be executed normally.

**Comment by glowkey** [comment]
This is expected behavior. DCGM diagnostics were removed as they increase the size of the container and are not used by DCGM-Exporter. If DCGM diagnostics are needed, the standalone DCGM container has that functionality.

**Comment by doddisam** [comment]
We have installed the DCGM exporter, which comes as part of the NVIDIA GPU Operator. Now, dcgmi diag is failing because of "nvss binary not found." Is there any workaround to get dcgmi diag outputs? Can you please here here ?
