### ISSUE TITLE
could not select device driver with capabilities "gpu"

### ISSUE THREAD

**Issue by dash042** [NVIDIA/dcgm-exporter#33]
Hi,

I am getting:

`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

**Comment by rickstaa** [comment]
I had the same problem. I fixed it by installing the nvidia-container-toolkit (see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).
