### ISSUE TITLE
Makefile missing DIST_DIR       := cmd/dcgm-exporter

### ISSUE THREAD

**Issue by jjziets** [NVIDIA/dcgm-exporter#331]
### What is the version?

 DCGM Exporter Release 3.3.6-3.4.2 

### What happened?

DIST_DIR       := cmd/dcgm-exporter is missing in the make file 

### What did you expect to happen?

so $DIST_DIR  is not defined thefore it needs to be defined in the make fil e

### What is the GPU model?

NA

### What is the environment?

NA

### How did you deploy the dcgm-exporter and what is the configuration?

NA

### How to reproduce the issue?

NA

### Anything else we need to know?

NA

**Comment by nvvfedorov** [comment]
@jjziets , Thank you for reporting the issue. We have merged the fix.
