### ISSUE TITLE
config csv DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS, but cannot get on metrics

### ISSUE THREAD

**Issue by suxwang** [NVIDIA/dcgm-exporter#338]
### What is the version?

3.3.5-3.4.1

### What happened?

i config csv that get metrics DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS, it's ruuning. but i cannot get it on http metrics.

here is my csv:

# ECC
DCGM_FI_DEV_ECC_SBE_VOL_TOTAL, counter, Total number of single-bit volatile ECC errors.

# Remapped rows
DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS, counter, Number of remapped rows for uncorrectable errors
DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS,   counter, Number of remapped rows for correctable errors
DCGM_FI_DEV_ROW_REMAP_FAILURE,           gauge,   Whether remapping of rows has failed

and this is my log:

EBU[0000] Loaded configuration                          dump="&{CollectorsFile:etc/rows_counter.csv Address::9400 CollectInterval:30000 Kubernetes:true KubernetesGPUIdType:uid CollectDCP:true UseOldNamespace:false UseRemoteHE:false RemoteHEInfo:localhost:5555 GPUDevices:{Flex:true MajorRange:[] MinorRange:[]} SwitchDevices:{Flex:true MajorRange:[] MinorRange:[]} CPUDevices:{Flex:true MajorRange:[] MinorRange:[]} NoHostname:false UseFakeGPUs:false ConfigMapData:none MetricGroups:[] WebSystemdSocket:false WebConfigFile: XIDCountWindowSize:300000 ReplaceBlanksInModelName:false Debug:true ClockEventsCountWindowSize:300000 NodeName:}"
INFO[0000] DCGM successfully initialized!               
INFO[0000] Collecting DCP Metrics                       
INFO[0000] Falling back to metric file 'etc/rows_counter.csv' 
INFO[0000] wxs Falling back to metric file err:no configmap data specified, ConfigMapData:'none' 
INFO[0000] record:[DCGM_FI_DEV_ECC_SBE_VOL_TOTAL  counter  Total number of single-bit volatile ECC errors.] 
INFO[0000] record:[DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS  counter  Number of remapped rows for uncorrectable errors] 
INFO[0000] record:[DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS    counter  Number of remapped rows for correctable errors] 
INFO[0000] record:[DCGM_FI_DEV_ROW_REMAP_FAILURE            gauge    Whether remapping of rows has failed] 
INFO[0000] counter:{[{310 DCGM_FI_DEV_ECC_SBE_VOL_TOTAL counter Total number of single-bit volatile ECC errors.} {393 DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS counter Number of remapped rows for uncorrectable errors} {394 DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS counter Number of remapped rows for correctable errors} {395 DCGM_FI_DEV_ROW_REMAP_FAILURE gauge Whether remapping of rows has failed}] []} 
INFO[0000] Initializing system entities of type: GPU    
DEBU[0000] System entities of type GPU initialized      
INFO[0000] Not collecting NvSwitch metrics; no fields to watch for device type: 3 
INFO[0000] Not collecting NvLink metrics; no fields to watch for device type: 6 
INFO[0000] Not collecting CPU metrics; no fields to watch for device type: 7 
INFO[0000] Not collecting CPU Core metrics; no fields to watch for device type: 8 
DEBU[0000] Counters are initialized                      dump="[{FieldID:310 FieldName:DCGM_FI_DEV_ECC_SBE_VOL_TOTAL PromType:counter Help:Total number of single-bit volatile ECC errors.} {FieldID:393 FieldName:DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS PromType:counter Help:Number of remapped rows for uncorrectable errors} {FieldID:394 FieldName:DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS PromType:counter Help:Number of remapped rows for correctable errors} {FieldID:395 FieldName:DCGM_FI_DEV_ROW_REMAP_FAILURE PromType:gauge Help:Whether remapping of rows has failed}]"
INFO[0000] Kubernetes metrics collection enabled!       
INFO[0000] Pipeline starting                            
INFO[0000] Starting webserver                           
level=info ts=2024-06-04T08:04:17.361Z caller=tls_config.go:313 msg="Listening on" address=[::]:9400
level=info ts=2024-06-04T08:04:17.361Z caller=tls_config.go:316 msg="TLS is disabled." http2=false address=[::]:9400

and this is my metrics:

# HELP DCGM_FI_DEV_ECC_SBE_VOL_TOTAL Total number of single-bit volatile ECC errors.
# TYPE DCGM_FI_DEV_ECC_SBE_VOL_TOTAL counter
DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{gpu="0",UUID="GPU-45edf842-5968-7192-5298-24b555f7e511",device="nvidia0",modelName="Tesla V100-PCIE-32GB",Hostname="nh-dc-nm130-c03-9u-gpu-4",container="",namespace="",pod=""} 0
DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{gpu="1",UUID="GPU-311aa146-3ea4-6cf4-5481-7c137c3008ad",device="nvidia1",modelName="Tesla V100-PCIE-32GB",Hostname="nh-dc-nm130-c03-9u-gpu-4",container="",namespace="",pod=""} 0
DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{gpu="2",UUID="GPU-87e04060-e68d-445b-2ee0-0a244c4233ae",device="nvidia2",modelName="Tesla V100-PCIE-32GB",Hostname="nh-dc-nm130-c03-9u-gpu-4",container="",namespace="",pod=""} 0
DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{gpu="3",UUID="GPU-fd7c36c3-ded3-d3bf-5b73-5cc3eacbc400",device="nvidia3",modelName="Tesla V100-PCIE-32GB",Hostname="nh-dc-nm130-c03-9u-gpu-4",container="",namespace="",pod=""} 0

you can see it cannot find DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS...

### What did you expect to happen?

hope these metrics can be find

**Comment by glowkey** [comment]
What is your GPU model?

**Comment by suxwang** [comment]
> What is your GPU model?

I have solve it. it's my gpu config cannot get it. I change another env and get it. thanks!
