### ISSUE TITLE
How to obtain the namespace , pod and container data

### ISSUE THREAD

**Issue by aikikia** [NVIDIA/dcgm-exporter#343]
### Ask your question

I deployed the dcgm-exporter daemonset successfully, but can't obtain the gpu metrics of the namespace, pod and container data. I only get the data about: gpu, modelName,uuid,hostname.
The versions of components are listed :
dcgm-exporter version: 3.3.-3.3.1-ubuntu22.04
k8s device plugin: 0.7.0
k8s:1.17.5
How to obtain the namepace, pod and container data？

**Comment by aikikia** [comment]
I have already satiesfied the two prerequisites,and **I successfully got the gpu mertics including this: gpu, modelName,uuid,hostname. But I cannot find the namespace, pod, and container data.**

Is it related to the version of the components?
dcgm-exporter version: 3.3.-3.3.1-ubuntu22.04
k8s device plugin: 0.7.0
k8s:1.17.5

> @aikikia, To see labels such as namespace, pod, and container, there are two prerequisites:
> 
> 1. The NVIDIA Device Plugin (https://github.com/NVIDIA/k8s-device-plugin/) must be installed;
> 2. Kubernetes mode must be enabled in the DCGM-Exporter by passing a command line parameter: -k, or set an environment variable DCGM_EXPORTER_KUBERNETES=true.

**Comment by nvvfedorov** [comment]
When prerequisites satisfied, you can run test workload as described here: https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#running-gpu-jobs

**Comment by aikikia** [comment]
> When prerequisites satisfied, you can run test workload as described here: https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#running-gpu-jobs

Perhaps my expression made you misunderstand, I already run the gp jobs sucessfully. But the problem is that I cannot obtain the gpu metric about container, pod name and namespace.
Now I only get these metrics:

**Comment by nvvfedorov** [comment]
@aikikia ,  If you have access to the K8S node, where you run the workload, can you try to build https://github.com/k8stopologyawareschedwg/podresourcesapi-tools/tree/main and run the client on the node? Unfortunately, kubectl doesn't provide commands to list "k8s.io/kubelet/pkg/apis/podresources/v1alpha1" API :(

As output of the command line you should see response something like this:

{
  "pod_resources": [
    {
      "name": "cuda-vector-add",
      "namespace": "default",
      "containers": [
        {
          "name": "cuda-vector-add",
          "devices": [
            {
              "resource_name": "nvidia.com/gpu",
              "device_ids": [
                "GPU-b9f9e81b-bee7-34bc-af17-132ef6592740"
              ]
            }
          ]
        }
      ]
    }
  ]
}

I am interesting to see entries with "resource_name": "nvidia.com/gpu" or "resource_name": "nvidia.com/mig-".


The DCGM Exporter uses the "k8s.io/kubelet/pkg/apis/podresources/v1alpha1" API to read information about kubernetes objects. 

If the DCGM Exporter doesn't have access to the PodResources API or Device Plugin is misconfigured, you may not see the mapping.

**Comment by aikikia** [comment]
Thanks. the podresourcesapi tools returns the error:E0619 11:15:38.962904 521824 main.go:105] "call failed" err="rpc error: code = Unimplemented desc = unknown service v1.PodResourcesLister" api="list". Maybe the kubernetes version(1.17.5) is too low...
If I need to adapt to the current k8s version, how can I modify DCGM to obtain pod metrics?

**Comment by nvvfedorov** [comment]
@aikikia, The issue that you see when you use the PodResourcesAPI is not a DCGM-exporter issue. It is something with the https://github.com/NVIDIA/k8s-device-plugin/ installation. I would recommend troubleshooting the device-plugin installation. You can report the issue here: https://github.com/NVIDIA/k8s-device-plugin/issues.
