### ISSUE TITLE
How to install dcgm-exporter on Windows Server?

### ISSUE THREAD

**Issue by LittleNewton** [NVIDIA/dcgm-exporter#344]
### Ask your question

Is there a release for Windows Server 2022?

I know almost all GPU servers are Linux-based, but a few are Windows-based.
```[tasklist]
### Tasks
```

**Comment by nvvfedorov** [comment]
Can you run dcgm-exporter in a docker container?

**Comment by LittleNewton** [comment]
@nvvfedorov Yes! I can run it in Linux docker container. So do you mean dcgm-exporter can work in windows docker desktop app?

**Comment by nvvfedorov** [comment]
@LittleNewton , We never tried, but it worth to try.  According to Docker Desktop documentation, Windows grant access to GPU for Docker containers. See: https://docs.docker.com/desktop/gpu/.

**Comment by nvvfedorov** [comment]
Also, you may try to use Ubuntu on WSL: https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2.

**Comment by LittleNewton** [comment]
@nvvfedorov , thanks for your advice. I have installed Docker Desktop on my Windows Server 2022 and dcgm-exporter works smoothly in this environment.

```
Docker Desktop rely
  --> WSL2 rely
      --> Hyper-V rely
            --> Security Policies for hardware isolation and software integrity (X, conflict with VMware Workstation Pro)
```

Now I give up VMware Workstation Pro because it said **VMware Workstation is not compatible with Device/Credential Guard**. Anyhow, it works. Thanks a lot!

**Comment by LittleNewton** [comment]
What's more, if you know how to make VMware workstation Pro and Docker Desktop compatible with each other, please let me know. :)
