### ISSUE TITLE
Why `DCGM_FI_DEV_PCIE_{TX,RX}_THROUGHPUT` is default instead of `DCGM_FI_PROF_PCIE_{TX,RX}_BYTES `?

### ISSUE THREAD

**Issue by koshieguchi** [NVIDIA/dcgm-exporter#354]
I find it very confusing that `DCGM_FI_DEV_PCIE_TX_THROUGHPUT` is still marked as default in files like `./etc/default-counters.csv`, despite the following statement in the DCGM Documentation (Version 3.3):

https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html#c.DCGM_FI_DEV_PCIE_TX_THROUGHPUT

> DCGM_FI_DEV_PCIE_TX_THROUGHPUT200¶
PCIe Tx utilization information.
Deprecated: Use DCGM_FI_PROF_PCIE_TX_BYTES instead.

In fact, as mentioned in [Get DCGM_FI_DEV_PCIE_TX_THROUGHPUT metric failed · Issue #167 · NVIDIA/dcgm-exporter](https://github.com/NVIDIA/dcgm-exporter/issues/167), I was able to obtain PCIe data by changing `DCGM_FI_DEV_PCIE_TX_THROUGHPUT` to `DCGM_FI_PROF_PCIE_TX_BYTES`.

Is there a reason why `DCGM_FI_DEV_PCIE_TX_THROUGHPUT` hasn't been updated to `DCGM_FI_PROF_PCIE_TX_BYTES `in the CSV files under `./etc`?

If it would be better to change it, I can create a pull request.

**Comment by glowkey** [comment]
Thanks for reporting this. We are planning to update the default watchlist for the next major release of DCGM-Exporter in the coming months and this change is included. Feel free to create an MR in the meantime if that is helpful for your site.

**Comment by koshieguchi** [comment]
Thanks for the reply!

> We are planning to update the default watchlist for the next major release of DCGM-Exporter in the coming months and this change is included.

That's good to hear!

> Feel free to create an MR in the meantime if that is helpful for your site.

I've created #357 to address this.
