### ISSUE TITLE
README link about "To integrate DCGM-Exporter with Prometheus and Grafana, see the full instructions in the user guide." is already invalid

### ISSUE THREAD

**Issue by jeffreyyjp** [NVIDIA/dcgm-exporter#358]
### What is the version?

3.3.6-3.4.2

### What happened?

https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/latest/
this link is already invalid.

### What did you expect to happen?

https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/latest/
should be valid.
![image](https://github.com/user-attachments/assets/d47d523a-4b8e-43fa-a439-07ca6cc2b336)

**Comment by nvvfedorov** [comment]
@jeffreyyjp, Thank you for reporting the issue with the documentation. Can you be more specific about what exactly is not valid and what would make the documentation valid for you? Thank you in advance.
