### ISSUE TITLE
dcgm-exporter log: No Kubelet socket, ignoring

### ISSUE THREAD

**Issue by jeffreyyjp** [NVIDIA/dcgm-exporter#362]
### What is the version?

3.3.6-3.4.2

### What happened?

After deployed dcgm-exporter as a daemonset, I checked any pod log, and it shows `No Kubelet socket, ignoring`

### What did you expect to happen?

The logs are clean

### What is the GPU model?

![image](https://github.com/user-attachments/assets/72c36768-dbdb-44f4-ac54-26679d318bde)

### What is the environment?

in k8s cluster

### How did you deploy the dcgm-exporter and what is the configuration?

I use helm, from the project `deploy` folder

### How to reproduce the issue?

After deploy it, check any pod log

**Comment by hive74** [comment]
in `values.yaml`
```
kubeletPath: "/path/to/your/kubelet/pod-resources"
```

**Comment by jeffreyyjp** [comment]
@hive74 
I used the default value for this:
```
# Path to the kubelet socket for /pod-resources
kubeletPath: "/var/lib/kubelet/pod-resources"
```
