### ISSUE TITLE
dcp metrics supports gpu architecture

### ISSUE THREAD

**Issue by lxzjd** [NVIDIA/dcgm-exporter#370]
### Ask your question

My environment is running dcgm-exporter, an error is reported：DCP metrics are supported for Volta, Turing or Ampere GPUs architectures only. Does dcgm currently support these architectures, and does Hopper not?

**Comment by nvvfedorov** [comment]
@lxzjd , Can you tell us about your environment and show output of the `nvidia-smi', also please share error log. Thank you in advance.

**Comment by lxzjd** [comment]
@nvvfedorov, 
This is my nvidia-smi output:
![image](https://github.com/user-attachments/assets/16d063d4-2e56-448b-88aa-3c8e558e2992)

error log：
![image](https://github.com/user-attachments/assets/b96cb5e4-c39e-41ed-a7d9-20602c0ff1e8)

My metrics profile default-counters.csv：
![image](https://github.com/user-attachments/assets/bee38928-abe6-483c-a3b6-115860207b50)

I know nvidia P40 certainly does not support the DCP metrics, but I'm very confused with this error, I tried the nvidia H800 don't have the error log, but curl http://localhost:9400/metrics also can't see the DCP related indicators. I just want to know what architectures dcgm's dcp metrics currently support.
![image](https://github.com/user-attachments/assets/cd2e49f3-6621-41a4-bfdf-6a3b006c9e42)

**Comment by nvvfedorov** [comment]
@lxzjd, it appears that on the H800 machine, you are using the default configuration for the DCGM-exporter, which does not include DCP metrics. Please update the configuration to use the dcp-metrics-included.csv file instead.

**Comment by lxzjd** [comment]
@nvvfedorov , thank you very much, my problem is solved, the H800 does get dcp metrics, I confused the default configuration of the k8s startup with the default configuration file of the docker startup. `DCP metrics are supported for Volta, Turing or Ampere GPUs architectures only` that error log is too easy to misunderstand. Can you change it?
