### ISSUE TITLE
DCGM Exporter does not collect individual pod metrics when MPS is enabled in Kubernetes

### ISSUE THREAD

**Issue by valafon** [NVIDIA/dcgm-exporter#388]
### What is the version?

3.1.8

### What happened?

When enabling MPS (Multi-Process Service) in a Kubernetes environment, DCGM Exporter stops creating metrics for individual pods that utilize the GPU through MPS. It seems that instead of per-pod metrics, only general metrics for the entire MPS daemon are available. The specific pod-related metrics disappear, which makes it impossible to track GPU usage per pod.

When MPS is enabled and multiple pods share a GPU, DCGM Exporter no longer provides separate metrics per pod.
It appears that DCGM Exporter only reports the overall usage of the MPS daemon itself.
Adding the environment variable CUDA_MPS_PIPE_DIRECTORY did not resolve the issue; metrics for individual pods are still not being collected.

### What did you expect to happen?

DCGM Exporter should continue to report GPU usage for individual pods, even when MPS is enabled, similar to how it works without MPS.

### What is the GPU model?

Tesla T4

### What is the environment?

Kubernetes, which has mounted /srv/mps directory and configure CUDA_MPS_PIPE_DIRECTORY variables to use MPS. MPS daemon running on worker node as a systemd unit.

### How did you deploy the dcgm-exporter and what is the configuration?

as systemd unit on kubernetes node

### How to reproduce the issue?

Enable MPS in a Kubernetes cluster.
Deploy multiple pods that use GPU resources via MPS.
Observe the metrics from DCGM Exporter and notice that only general metrics from the MPS daemon are available, but metrics per pod are missing.

**Comment by glowkey** [comment]
DCGM-Exporter does not currently support pod metrics with an MPS configuration. Unfortunately, support is not in the roadmap.
