### ISSUE TITLE
DCGM_FI_PROF_GR_ENGINE_ACTIVE not emitted on system with more than one GPU

### ISSUE THREAD

**Issue by chipzoller** [NVIDIA/dcgm-exporter#395]
### Ask your question

We are seeing that the metric `DCGM_FI_PROF_GR_ENGINE_ACTIVE` is not being emitted by DCGM Exporter (3.6.0 and 3.4.2 tested) on a node with two M60 GPUs however the older metric `DCGM_FI_DEV_GPU_UTIL` is. Other nodes which only have a single T4 show that `DCGM_FI_PROF_GR_ENGINE_ACTIVE` is being emitted as expected. It appears to make no difference whether both GPUs are being allocated or not on the 2-GPU Node when it comes to the ENGINE_ACTIVE metric.

This is shown in the logs for that Pod but don't understand why when it isn't shown for other DCGM Exporter Pods on other nodes with single T4s.

```log
Not collecting DCP metrics: This request is serviced by a module of DCGM that is not currently loaded
Skipping line 19 ('DCGM_FI_PROF_GR_ENGINE_ACTIVE'): metric not enabled
```

Is this a bug somewhere or working as intended? Are DCP metrics not supported on M60 cards? If it's intended, why is this the behavior and is there any alternative to get overall GPU usage without falling back to GPU_UTIL?

**Comment by glowkey** [comment]
Unfortunately, the M60 does not support profiling metrics. Volta or newer is required for PROF metric support. DCGM_FI_DEV_GPU_UTIL is the recommended utilization metric for that GPU.

**Comment by chipzoller** [comment]
Thanks very much, didn't know that and even checked DCGM docs. Do you think this is valuable to document for others? If so, where?
