### ISSUE TITLE
Maintain uniformity with helm chart and static yaml's

### ISSUE THREAD

**Issue by Indresh2410** [NVIDIA/dcgm-exporter#402]
### What is the version?

3.3.8-3.6.0

### What happened?

We are running workloads in AWS Cloud and when we are deploying dcgm-exporter.yaml, pod is not coming up with below error

`host engine is running as non-root`

### What did you expect to happen?

The pod should be up and running seamlessly. Looks like in helm, we are passing additional privileges to the pod under securityContext

SYS_ADMIN
https://github.com/NVIDIA/dcgm-exporter/blob/f796076fbc139e3b744c084bb977d968016aca79/deployment/values.yaml#L88

whereas in static it is not present. Hence it is throwing errors. Once added, it is running smoothly
https://github.com/NVIDIA/dcgm-exporter/blob/f796076fbc139e3b744c084bb977d968016aca79/dcgm-exporter.yaml

### What is the environment?

DCGM running in AWS environment

### How to reproduce the issue?

Deploy dcgm-exporter.yaml present in latest release

### Anything else we need to know?

Happy to contribute a PR to fix it if this is a bug

**Comment by nvvfedorov** [comment]
@Indresh2410 , Thank you for reporting about the issue. We are accepting the PRs.

**Comment by Indresh2410** [comment]
Thanks @nvvfedorov . Have raised PR https://github.com/NVIDIA/dcgm-exporter/pull/403

Can you please review the above?

**Comment by Yvanll** [comment]
Is SYS_ADMIN really necessary in 3.6.0? What specific feature introduced in this version caused the issue is worth discussing.

**Comment by Indresh2410** [comment]
Hi @Yvanll . We were trying to run in eks accelerated AMI for GPU which was released recently in which it was erroring out
https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-accelerated-amis-now-available/

**Comment by Yvanll** [comment]
Hi @Indresh2410. I'm actually wondering what new feature in dcgm-exporter 3.6.0 needs SYS_ADMIN, since the last version 3.5.0 is working fine without this flag.

**Comment by Indresh2410** [comment]
Hey @Yvanll . Verified for 3.5.0 as well. Looks like even that is not working without SYS_ADMIN when deployed in eks accelerated AMI for GPU. Not sure if the issue is version specific

**Comment by Yvanll** [comment]
Hi @Indresh2410. Thanks for verifying. It's not version issue. I have tested both the 3.6.0 and 3.5.0 working fine on some devices. The ' running as non-root' error is raised by a dcgm_interface in dcgm_agent.h named dcgmWatchFields from [DCGM](https://github.com/NVIDIA/DCGM/blob/903d745504f50153be8293f8566346f9de3b3c93/dcgmlib/dcgm_agent.h#L943) but I don't know the further details.

**Comment by Indresh2410** [comment]
Agreed @Yvanll . Below is full error thrown

`time="2024-10-24T15:52:02Z" level=fatal msg="Failed to watch metrics: Error watching fields: Host engine is running as non-root"  `

If it is fine for you, can we track the above as a separate issue and take it to closure? Asking this so that we can maintain uniformity across static and helm chart yaml's. Kindly let me know your thoughts on this

**Comment by Yvanll** [comment]
It's fine to me for uniformity, however a non-privileged solution is much perfered if possible.

**Comment by Indresh2410** [comment]
Thanks for creating a new issue @Yvanll . Since this requires some debugging and by default helm applies SYS_ADMIN capabilities to securityContext, feel for uniformity we can proceed further imo. Will rename the issue accordingly as well considering new issue is opened. Please let me know your thoughts on this 

Once root cause is identified, we can remove from both the places
