### ISSUE TITLE
Is RTX4090 supported?

### ISSUE THREAD

**Issue by fzyzcjy** [NVIDIA/dcgm-exporter#404]
Hi thanks for the tool! https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/getting-started.html says:

> DCGM currently supports the following products and environments: ... All Maxwell and newer non-datacenter (e.g. GeForce or Quadro) GPUs

Thus I guess the answer is yes. However, from some issues in this repo, it seems GeForce cards are not supported. I personally also fail to do so...

**Comment by glowkey** [comment]
Not all DCGM features are supported on RTX4090, specifically profiling metrics. See the note on "Platform Support" in the DCGM documentation: https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#platform-support

**Comment by fzyzcjy** [comment]
I see, thank you!
