### ISSUE TITLE
Can dcgm-export be used with Apptainer instead of Docker?

### ISSUE THREAD

**Issue by sorenwacker** [NVIDIA/dcgm-exporter#410]
### Ask your question

Our cluster does not use Docker, so I am trying to set this up with Apptainer:

```
BootStrap: docker
From: nvcr.io/nvidia/k8s/dcgm-exporter:latest

%environment
    export NVIDIA_VISIBLE_DEVICES=all

%startscript
  echo "Starting DCGM Exporter..."
  /usr/bin/dcgm-exporter
```

But when I run this I get:

```
apptainer exec instance://dcgm-exporter sh
Apptainer> /usr/bin/dcgm-exporter
INFO[0000] Starting dcgm-exporter                       
Error: Failed to initialize NVML
FATA[0000] Error starting nv-hostengine: DCGM initialization error 
Apptainer> nvidia-smi
Failed to initialize NVML: Insufficient Permissions
Apptainer> 
```

`nvidia-smi` is available outside the container and the container is started with the `--nv` flag.

**Comment by nvvfedorov** [comment]
It sounds like, you want to connect the dcgm-exporter to remote nv-hostengine instance. You can do this by providing "-r [hostname:port]" parameter to the dcgm-exporter commandline.

**Comment by sorenwacker** [comment]
Yes, that is the longterm goal, right now I am just trying to run it with Apptainer locally. It works in docker, but with Apptainer I get that error message above. I assume that the dcgm-exporter needs some previleges that Apptainer does not grant?

Maybe I need more configuration or some environment variables?

## Apptainer.def
```
BootStrap: docker
From: nvcr.io/nvidia/k8s/dcgm-exporter:latest

%environment
    export NVIDIA_VISIBLE_DEVICES=all

%startscript
  echo "Starting DCGM Exporter..."
  /usr/bin/dcgm-exporter
```

**Comment by sorenwacker** [comment]
Never mind. That was a problem with the nvidia driver on the host system.
