### ISSUE TITLE
Understand how exporter is able to query metrics

### ISSUE THREAD

**Issue by Indresh2410** [NVIDIA/dcgm-exporter#421]
### Ask your question

Hi team. Whenever we try to fetch gpu metrics from underlying instance within container using dcgmi cli, we are getting connection refused
`Error: unable to establish a connection to the specified host
Error: Unable to connect to host engine. Host engine connection invalid/disconnected`

But however the exporter is able to query and generate metrics. Is it possible to replicate the same behaviour used by exporter via dcgmi as well i.e without listening to remote connections

Or can someone please let us know how exporter is querying the metrics from underlying instance?

**Comment by glowkey** [comment]
DCGM-Exporter uses the DCGM library in [embedded mode ](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-admin.html#_CPPv417dcgmStartEmbedded19dcgmOperationMode_tP12dcgmHandle_t). This means it does not need to communicate with an external DCGM nv-hostengine. The 'dcgmi' command does not have the same functionality.

**Comment by Indresh2410** [comment]
Thanks for helping out @glowkey 🙂
