### ISSUE TITLE
Running dcgm-exporter with Docker

### ISSUE THREAD

**Issue by maxclac** [NVIDIA/dcgm-exporter#44]
Hi!

I am trying to run dcgm-exporter with Docker like this:

```
DCGM_EXPORTER_VERSION=2.1.4-2.3.1 && \
docker run -d --rm \
   --gpus all \
   --net host \
   --cap-add SYS_ADMIN \
   nvcr.io/nvidia/k8s/dcgm-exporter:${DCGM_EXPORTER_VERSION}-ubuntu20.04 \
   -f /etc/dcgm-exporter/dcp-metrics-included.csv
```

What I would like to do is modify this dcp-metrics-included.csv file. How can I do this? Do I need to clone the repo, modify the file there and rebuild the Docker image?

Best regards

**Comment by glowkey** [comment]
You can do that. You could also create a separate csv file with your custom metrics, mount it within the container and use the -f flag to point to the newly mounted custom metrics file.

**Comment by glowkey** [comment]
Unfortunately you cannot pass a directory. dcgm-exporter currently only accepts a single file or, in kubernetes, a configmap volume.
