### ISSUE TITLE
the tests fail

### ISSUE THREAD

**Issue by pint1022** [NVIDIA/dcgm-exporter#57]
try to run the test under pkg/dcgmexporter, it fails.
here is the steps:
cd pkg/dcgmexporter
go test
2022/03/21 09:42:57 proto: duplicate proto type registered: v1alpha1.ListPodResourcesRequest
2022/03/21 09:42:57 proto: duplicate proto type registered: v1alpha1.ListPodResourcesResponse
2022/03/21 09:42:57 proto: duplicate proto type registered: v1alpha1.PodResources
2022/03/21 09:42:57 proto: duplicate proto type registered: v1alpha1.ContainerResources
2022/03/21 09:42:57 proto: duplicate proto type registered: v1alpha1.ContainerDevices
--- FAIL: TestDCGMCollector (0.00s)
    gpu_collector_test.go:35:
                Error Trace:    gpu_collector_test.go:35
                Error:          Received unexpected error:
                                libdcgm.so not Found
                Test:           TestDCGMCollector
/tmp/go-build21440241/b001/dcgmexporter.test: symbol lookup error: /tmp/go-build21440241/b001/dcgmexporter.test: undefined symbol: dcgmGetAllDevices
exit status 127
FAIL    github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter        0.016s

is there any settings to run the test?

**Comment by glowkey** [comment]
> libdcgm.so not Found

The libdcgm.so file is included in the datacenter-gpu-manager package. That package must be installed on any system running dcgm-exporter.

**Comment by glowkey** [comment]
Only if you want to address the error in your first message.

**Comment by pint1022** [comment]
after installing  datacenter-gpu-manager, the test runs.
