### ISSUE TITLE
Container, namespace and pod informations on metrics

### ISSUE THREAD

**Issue by hahayyum** [NVIDIA/dcgm-exporter#58]
Why in my dcgm-exporter /metrics,doesnt show container, namespace and pod informations?
In every metric comes like this container="",namespace="",pod=""

# HELP DCGM_FI_DEV_SM_CLOCK SM clock frequency (in MHz).
# TYPE DCGM_FI_DEV_SM_CLOCK gauge
DCGM_FI_DEV_SM_CLOCK{gpu="0",UUID="GPU-55274b56-9033-f166-7723-77088b0ff94d",device="nvidia0",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="1",UUID="GPU-dad58a68-8239-6bb7-1f07-539b85fabfee",device="nvidia1",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="2",UUID="GPU-a29d2dc7-d18a-858c-a87b-f81eb1384333",device="nvidia2",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="3",UUID="GPU-4b2cedc3-89f9-dde9-ce2f-3b8d40dbe531",device="nvidia3",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="4",UUID="GPU-58fae45b-e5a5-0c62-d478-8ff7c485e74e",device="nvidia4",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 1335
DCGM_FI_DEV_SM_CLOCK{gpu="5",UUID="GPU-5f10c931-56f5-ad53-4ce6-54e98a17d07f",device="nvidia5",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="6",UUID="GPU-d56e5edb-72a1-d150-0ce0-dfe2c3092263",device="nvidia6",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
DCGM_FI_DEV_SM_CLOCK{gpu="7",UUID="GPU-7d2d5bed-82d2-c5fd-1fee-ccc74692ff91",device="nvidia7",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 135
# HELP DCGM_FI_DEV_MEM_CLOCK Memory clock frequency (in MHz).
# TYPE DCGM_FI_DEV_MEM_CLOCK gauge
DCGM_FI_DEV_MEM_CLOCK{gpu="0",UUID="GPU-55274b56-9033-f166-7723-77088b0ff94d",device="nvidia0",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="1",UUID="GPU-dad58a68-8239-6bb7-1f07-539b85fabfee",device="nvidia1",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="2",UUID="GPU-a29d2dc7-d18a-858c-a87b-f81eb1384333",device="nvidia2",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="3",UUID="GPU-4b2cedc3-89f9-dde9-ce2f-3b8d40dbe531",device="nvidia3",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="4",UUID="GPU-58fae45b-e5a5-0c62-d478-8ff7c485e74e",device="nvidia4",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="5",UUID="GPU-5f10c931-56f5-ad53-4ce6-54e98a17d07f",device="nvidia5",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="6",UUID="GPU-d56e5edb-72a1-d150-0ce0-dfe2c3092263",device="nvidia6",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850
DCGM_FI_DEV_MEM_CLOCK{gpu="7",UUID="GPU-7d2d5bed-82d2-c5fd-1fee-ccc74692ff91",device="nvidia7",modelName="NVIDIA TITAN V",Hostname="dcgm-exporter-lcxpl",container="",namespace="",pod=""} 850

[root@master1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.19.4-20211018+1dd39f5bc682f8cb90cdc7cc217c00465d00e1e0", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.19.4-20211018+1dd39f5bc682f8cb90cdc7cc217c00465d00e1e0", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

kubectl create -f https://raw.githubusercontent.com/NVIDIA/dcgm-exporter/master/dcgm-exporter.yaml

HOST:
[root@gpu34-tianv ~]#  nvidia-smi
Tue Mar 22 15:46:52 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN V      On   | 00000000:3D:00.0 Off |                  N/A |
| 28%   27C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN V      On   | 00000000:3E:00.0 Off |                  N/A |
| 28%   27C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN V      On   | 00000000:3F:00.0 Off |                  N/A |
| 28%   26C    P8    22W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA TITAN V      On   | 00000000:40:00.0 Off |                  N/A |
| 28%   29C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA TITAN V      On   | 00000000:43:00.0 Off |                  N/A |
| 45%   63C    P2   192W / 250W |  10889MiB / 12066MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA TITAN V      On   | 00000000:44:00.0 Off |                  N/A |
| 28%   26C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA TITAN V      On   | 00000000:45:00.0 Off |                  N/A |
| 28%   26C    P8    25W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA TITAN V      On   | 00000000:46:00.0 Off |                  N/A |
| 28%   28C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    4   N/A  N/A    650485      C   ./gpu_burn                      10885MiB |
+-----------------------------------------------------------------------------+

BUT  dcgm-exporter Container：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN V      On   | 00000000:3D:00.0 Off |                  N/A |
| 28%   27C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN V      On   | 00000000:3E:00.0 Off |                  N/A |
| 28%   27C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN V      On   | 00000000:3F:00.0 Off |                  N/A |
| 28%   26C    P8    22W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA TITAN V      On   | 00000000:40:00.0 Off |                  N/A |
| 28%   29C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA TITAN V      On   | 00000000:43:00.0 Off |                  N/A |
| 45%   62C    P2   190W / 250W |  10889MiB / 12066MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA TITAN V      On   | 00000000:44:00.0 Off |                  N/A |
| 28%   26C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA TITAN V      On   | 00000000:45:00.0 Off |                  N/A |
| 28%   26C    P8    25W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA TITAN V      On   | 00000000:46:00.0 Off |                  N/A |
| 28%   28C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by glowkey** [comment]
These fields are populated by kubernetes when a pod requests and is assigned gpu resources. See the following documentation: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by hahayyum** [comment]
@glowkey Thank you. Now we have the data！
