### ISSUE TITLE
Supported CPU architecture

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/dcgm-exporter#6]
Hi 

Please let me confirm the supported CPU architecture.
Is it possible to run the dcgm-exporter on the ppc64le?
 -> It is OK to run on ”bare metal” or "container".

Best regards.
Kaka

**Comment by nikkon-dev** [comment]
The dcgm-exporter, as we release it, is not compiled for ppc64le architecture. But, DCGM itself supports amd64, ppc64le and aarch64 architectures. That means you should be able to compile dcgm-exporter for ppc64le using DCGM and Cuda for that platform. That was not tested and not going to be officially supported, though.

WBR,
Nik

**Comment by Kaka1127** [comment]
@nikkon-dev 

Thank you for your answer. I understand.

Best regards.
kaka
