### ISSUE TITLE
nvidia-dcgm-exporter pod keeps crashing

### ISSUE THREAD

**Issue by soumen-ghosh** [NVIDIA/dcgm-exporter#61]
I have installed through 'microk8s enable gpu'. But the nvidia-dcgm-exporter-* pod keeps crashing - the control plane machine is not a gpu. But one of worker nodes is gpu. 

gpu-operator-resources         nvidia-dcgm-exporter-wjgff                                    0/1     CrashLoopBackOff   46 (2m52s ago)   4h18

time="2022-04-15T00:35:52Z" level=info msg="Starting dcgm-exporter"
time="2022-04-15T00:35:52Z" level=info msg="Attemping to connect to remote hostengine at 10.194.160.35:5555"
time="2022-04-15T00:36:52Z" level=info msg="DCGM successfully initialized!"
time="2022-04-15T00:36:52Z" level=info msg="Not collecting DCP metrics: Error getting supported metrics: Host engine connection invalid/disconnected"
time="2022-04-15T00:36:52Z" level=warning msg="Skipping line 55 ('DCGM_FI_PROF_GR_ENGINE_ACTIVE'): DCP metrics not enabled"
time="2022-04-15T00:36:52Z" level=warning msg="Skipping line 58 ('DCGM_FI_PROF_PIPE_TENSOR_ACTIVE'): DCP metrics not enabled"
time="2022-04-15T00:36:52Z" level=warning msg="Skipping line 59 ('DCGM_FI_PROF_DRAM_ACTIVE'): DCP metrics not enabled"
time="2022-04-15T00:36:52Z" level=warning msg="Skipping line 63 ('DCGM_FI_PROF_PCIE_TX_BYTES'): DCP metrics not enabled"
time="2022-04-15T00:36:52Z" level=warning msg="Skipping line 64 ('DCGM_FI_PROF_PCIE_RX_BYTES'): DCP metrics not enabled"
time="2022-04-15T00:36:52Z" level=fatal msg="Error getting devices count: Host engine connection invalid/disconnected"

(base) root@pbm088:~# kubectl describe  pod/nvidia-dcgm-exporter-wjgff -n gpu-operator-resources
Name:                 nvidia-dcgm-exporter-wjgff
Namespace:            gpu-operator-resources
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 itml09-vm1/10.194.160.35
Start Time:           Thu, 14 Apr 2022 13:20:48 -0700
Labels:               app=nvidia-dcgm-exporter
                      controller-revision-hash=5ddb68bf9d
                      pod-template-generation=1
Annotations:          cni.projectcalico.org/podIP: 10.1.241.16/32
                      cni.projectcalico.org/podIPs: 10.1.241.16/32
Status:               Running
IP:                   10.1.241.16
IPs:
  IP:           10.1.241.16
Controlled By:  DaemonSet/nvidia-dcgm-exporter
Init Containers:
  toolkit-validation:
    Container ID:  containerd://0225e964397202c518b818711f65f6e4197a71af25298e2438e71522a395d943
    Image:         nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.8.2
    Image ID:      nvcr.io/nvidia/cloud-native/gpu-operator-validator@sha256:a07fd1c74e3e469ac316d17cf79635173764fdab3b681dbc282027a23dbbe227
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 14 Apr 2022 13:20:50 -0700
      Finished:     Thu, 14 Apr 2022 13:20:50 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fwz6d (ro)
Containers:
  nvidia-dcgm-exporter:
    Container ID:   containerd://abbf1b909c33a0b0ba2d28b48b9c0c45fbbf2e0693021233b5521c40433a7f10
    Image:          nvcr.io/nvidia/k8s/dcgm-exporter:2.2.9-2.4.0-ubuntu20.04
    Image ID:       nvcr.io/nvidia/k8s/dcgm-exporter@sha256:25d60a39b316702809d9645d175fea0aa8e51fddf749e334ae2f033a0590485f
    Port:           9400/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 14 Apr 2022 17:41:57 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 14 Apr 2022 17:35:52 -0700
      Finished:     Thu, 14 Apr 2022 17:36:52 -0700
    Ready:          True
    Restart Count:  47
    Environment:
      NODE_IP:                       (v1:status.hostIP)
      DCGM_EXPORTER_LISTEN:         :9400
      DCGM_EXPORTER_KUBERNETES:     true
      DCGM_EXPORTER_COLLECTORS:     /etc/dcgm-exporter/dcp-metrics-included.csv
      DCGM_REMOTE_HOSTENGINE_INFO:  $(NODE_IP):5555
    Mounts:
      /var/lib/kubelet/pod-resources from pod-gpu-resources (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fwz6d (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pod-gpu-resources:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pod-resources
    HostPathType:
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:
  kube-api-access-fwz6d:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.deploy.dcgm-exporter=true
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  2m5s (x993 over 4h21m)  kubelet  Back-off restarting failed container

What should I check for to resolve this?

**Comment by nikkon-dev** [comment]
Hi,

You need to check if dcgm-exporter is able to connect to the remove nv-hostengine `DCGM_REMOTE_HOSTENGINE_INFO: $(NODE_IP):5555`.

There are two modes dcgm-exporter supports: 1) dcgm-exporter connects to a standalone nv-hostengine working in another container or right on the node. 2) dcgm-exporter runs embedded hostengine and does not need to connect to any other hostengine on port 5555. In the second mode, dcgm-exporter would fail to initialize some modules if there is another nv-hostengine process on the same physical machine.

You need to see the dcgm-exporter command line to understand the mode it's running.

**Comment by soumen-ghosh** [comment]
Hi,

> You need to see the dcgm-exporter command line to understand the mode it's running.
Can you help with some pointers on how do I check this? I'm trying this for the 1st time.

**Comment by nikkon-dev** [comment]
Please, take a look here https://github.com/NVIDIA/dcgm-exporter/blob/0869a2ac03c73e82715438f44d2ecf2491049139/deployment/values.yaml#L23
