### ISSUE TITLE
Does this exporter support monitoring AWS virtual gpu via AWS virtual gpu device plugin?

### ISSUE THREAD

**Issue by jaggerwang** [NVIDIA/dcgm-exporter#69]
I've an AWS EKS cluster with GPU nodes, and installed AWS virtual gpu device plugin to share GPU between different pods. It seems that this exporter dependent on Nvidia device plugin, but AWS virtual gpu device plugin cannot work with Nvidia device plugin together.

**Comment by nikkon-dev** [comment]
@jaggerwang,

DCGM supports virtual devices in the passthrough mode only. The hardware counters are not virtualized.
