### ISSUE TITLE
Latest Release bugs 2.4.5-2.6.7 - metrics missing

### ISSUE THREAD

**Issue by hassanbabaie** [NVIDIA/dcgm-exporter#71]
When upgrading to 2.4.5-2.6.7 we lose access to:
DCGM_FI_DEV_FB_USED
DCGM_FI_DEV_FB_TOTAL
DCGM_FI_DEV_FB_FREE

Going back to 2.3.5-2.6.5 resolves the issue

Also it looks like DCGM 2.4.5 should now support the following, however it appears the new release which uses 2.4.5 does not yet, this is more a question than an issue
DCGM_FI_PROF_PIPE_TENSOR_IMMA_ACTIVE
DCGM_FI_PROF_PIPE_TENSOR_HMMA_ACTIVE

Servers are running 470.57.02

**Comment by glowkey** [comment]
Thanks for reporting this. Can you describe what you mean by "lose access", are they reporting "0"?

**Comment by glowkey** [comment]
We have submitted an internal fix for the missing FB fields and that will be available in the next release.

The other fields you asked about are available in DCGM but not part of the default watched fields.

**Comment by glowkey** [comment]
The missing metrics will also be included in the next release.
