### ISSUE TITLE
Will DCGM_FI_DEV_FB_USED_PERCENT be coming to the exporter in the next release

### ISSUE THREAD

**Issue by hassanbabaie** [NVIDIA/dcgm-exporter#77]
Hi @glowkey I noticed this [PR Synchronize and update headers from DCGM 2.4.5](https://github.com/NVIDIA/go-dcgm/commit/ede63d11c9e7d11f17f217648a1adfc824db37df)

Does that mean DCGM_FI_DEV_FB_USED_PERCENT will also be coming to the next exporter release? It would be extremely handy

Thanks

**Comment by nikkon-dev** [comment]
Hi @hassanbabaie,

Yes, that's the plan.
