### ISSUE TITLE
Issue running 2.4.6-2.6.8

### ISSUE THREAD

**Issue by hassanbabaie** [NVIDIA/dcgm-exporter#80]
@glowkey where these any breaking changes in the latest release?

I just tested the release by swapping the docker images out and I get the following error:

```
setting up csv
/etc/dcgm-exporter/dcp-metrics-bolt.csv
done
time="2022-07-19T14:22:40Z" level=info msg="Starting dcgm-exporter"
time="2022-07-19T14:22:41Z" level=info msg="DCGM successfully initialized!"
time="2022-07-19T14:22:41Z" level=info msg="Collecting DCP Metrics"
time="2022-07-19T14:22:41Z" level=info msg="No configmap data specified, falling back to metric file /etc/dcgm-exporter/dcp-metrics-bolt.csv"
time="2022-07-19T14:22:41Z" level=fatal msg="Error getting device busid: API version mismatch"
```

Rolling back to 2.3.5-2.6.5 removed the issue and I didn't see this issue on 2.4.5-2.6.7 but that release had other metric issues.

**Comment by glowkey** [comment]
We are investigating this issue related to the go-dcgm bindings and believe we have a fix. Can you describe your setup?

**Comment by hassanbabaie** [comment]
Thanks @glowkey I'm testing this on k8s worker nodes using V100-16GB and A100-40GB GPUs and in this case the 470 driver

**Comment by glowkey** [comment]
Are you using gpu-operator? If so, which version of the dcgm container is running?

**Comment by hassanbabaie** [comment]
@glowkey no, just the DaemonSet and associated Service

**Comment by glowkey** [comment]
2.4.6-2.6.9 has been pushed. Please update this thread if there are still issues.

**Comment by hassanbabaie** [comment]
yes this fixed that issue, I see another issue now and will start a new thread for that now
