### ISSUE TITLE
Metric DCGM_FI_DEV_FB_RESERVED does not appear to be reported by dcgm-exporter (2.4.6-2.6.9)

### ISSUE THREAD

**Issue by hassanbabaie** [NVIDIA/dcgm-exporter#83]
We used to have just:

```
DCGM_FI_DEV_FB_FREE
DCGM_FI_DEV_FB_USED
DCGM_FI_DEV_FB_TOTAL
```

We were calculating the `%` by doing the following:

`DCGM_FI_DEV_FB_USED` / `DCGM_FI_DEV_FB_TOTAL`

I've tried to move this over to the new metric `DCGM_FI_DEV_FB_USED_PERCENT` to make everything easier however this is now based of a new metric added in 2.4.5 which is DCGM_FI_DEV_FB_RESERVED ((instead off just the old metrics).

`DCGM_FI_DEV_FB_USED_PERCENT` = `(DCGM_FI_DEV_FB_RESERVED + DCGM_FI_DEV_FB_USED) / DCGM_FI_DEV_FB_TOTAL`

This means as an example on an unused GPU where we used to get `0%` we now get `0.000008%` on V100-16GB.

I'm trying to sanity check this and I think this is coming from what I assume means GPU System reserved: `DCGM_FI_DEV_FB_RESERVED` but this metric is not being reported by dcgm-exporter.

**Comment by glowkey** [comment]
You are correct that, if supported by the driver, DCGM_FI_DEV_FB_RESERVED is part of the calculation. You can validate this using 'nvidia-smi -q -d MEMORY' to show the inputs DCGM is using.

**Comment by hassanbabaie** [comment]
Thanks @glowkey sorry my long winded rant distracted from what I was reporting;

I think dcgm-exporter should be reporting `DCGM_FI_DEV_FB_RESERVED` but it is not, it's returning no data

**Comment by glowkey** [comment]
@hassanbabaie, That field is not enabled by default. Did you explicitly enable it? Or are you asking to have it added to the default list? Unfortunately it is only supported on recent drivers.

**Comment by hassanbabaie** [comment]
Thanks @glowkey yes I added it as an arg

```
echo "DCGM_FI_DEV_FB_USED_PERCENT,gauge,Percentage used (Used+Reserved/Total) of Frame Buffer Range 0-1." >> /etc/dcgm-exporter/dcp-metrics-bolt.csv;
echo "DCGM_FI_DEV_FB_RESERVED,gauge,Reserved Frame Buffer in MB." >> /etc/dcgm-exporter/dcp-metrics-bolt.csv;
```

Given the it shows a non 0 percent for `DCGM_FI_DEV_FB_USED_PERCENT` then I think that means it should work but is not reporting?

Also just to confirm if DCGM_FI_DEV_FB_RESERVED doesn't work constituently for all drivers then I think DCGM_FI_DEV_FB_USED_PERCENT should be changed to give consistency to users?


Currently:

`DCGM_FI_DEV_FB_USED_PERCENT = (DCGM_FI_DEV_FB_RESERVED + DCGM_FI_DEV_FB_USED) / DCGM_FI_DEV_FB_TOTAL`

TO:

`DCGM_FI_DEV_FB_USED_PERCENT = (DCGM_FI_DEV_FB_USED) / DCGM_FI_DEV_FB_TOTAL - DCGM_FI_DEV_FB_RESERVED
`

**Comment by glowkey** [comment]
We are planning on making this change to DCGM_FI_DEV_FB_USED_PERCENT in the next version of DCGM.
