### ISSUE TITLE
No exported_pod in metrics

### ISSUE THREAD

**Issue by Muscule** [NVIDIA/dcgm-exporter#85]
> @nikkon-dev I got it working! I needed to add this to my env as well since it was the [non-default option](https://github.com/NVIDIA/dcgm-exporter/blob/d40847d147eb8da211c5fec4c9c840729053eab7/cmd/dcgm-exporter/main.go#L142)
> 
> ```
> - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
>               value: "device-name"
> ```
> 
> Now I see my pod coming as exported_pod="my-pod-zzzzzzz-xxxx". Thanks a ton for all your help here!

Didn't help with gpu-operator v1.11.0

_Originally posted by @Muscule in https://github.com/NVIDIA/dcgm-exporter/issues/27#issuecomment-1195387406_

**Comment by Muscule** [comment]
Which version of dcgm-exporter can I use to see exported_pod?

**Comment by Muscule** [comment]
I use dcgm-exporter-2.4.5-2.6.7-ubuntu20.04

**Comment by Muscule** [comment]
2.2.9-2.4.0-ubuntu20.04 didn't help

Nvidia gpu-operator 1.11.0

**Comment by jojotong** [comment]
You can check your servicemonitor config. Do you add `honorLabels: true` ？

**Comment by Muscule** [comment]
> You can check your servicemonitor config. Do you add `honorLabels: true` ？

Yes

**Comment by Muscule** [comment]
curl localhost:9400/metrics gives nothing with "exported"

**Comment by Muscule** [comment]
Is there any solution?

**Comment by wotkddl21** [comment]
The exported_pod label is made by the prometheus, which is called server-side labels.
Let assume you set the honor_label to "false".
Then when the prometheus scrapes the metrics, there could be some rules to relabel the source labels.
If you are using the servicemonitor to scrape dcgm-exporter in the kubernetes, then the additional label "node", "pod" and "namespace" would be created by the prometheus.
So these new labels will crash with the source labels from the dcgm-exporter.
In this case, the prometheus adds the prefix "exported" to the labels from the scraped data.

But you set honor_label to true, then the prometheus won't make server-side labels, which is keeping the source labels.

Check the link below
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

``` bash
# If honor_labels is set to "true", label conflicts are resolved by keeping label
# values from the scraped data and ignoring the conflicting server-side labels.
#
# If honor_labels is set to "false", label conflicts are resolved by renaming
# conflicting labels in the scraped data to "exported_<original-label>" (for
# example "exported_instance", "exported_job") and then attaching server-side
# labels. 
```

**Comment by mossad-zika** [comment]
source metrics  don't show me the info
 
<img width="602" alt="Screenshot 2023-08-11 at 20 03 11" src="https://github.com/NVIDIA/dcgm-exporter/assets/13749031/bee2e727-4b33-48ea-a156-34872dd925d0">

**Comment by mossad-zika** [comment]
SM also doesn't do any relabel by default

https://github.com/NVIDIA/dcgm-exporter/blob/main/deployment/templates/service-monitor.yaml

**Comment by mossad-zika** [comment]
```
extraEnv:
  - name: "DCGM_EXPORTER_KUBERNETES"
    value: "true"
  - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
    value: "uid"
```

seems working, but testing now

BTW: nvidia's products are awesome and docs are total shit

**Comment by tanmay6414** [comment]
I have added this env variable still not getting exported_pod in metrics
