### ISSUE TITLE
how to interpret DCGM_FI_PROF_PCIE_TX_BYTES metric

### ISSUE THREAD

**Issue by Omoong** [NVIDIA/dcgm-exporter#87]
im trying testing some metrics on dcgm-exporter and ran into following metrics and just could not figure out how the following metrics work. 

DCGM_FI_PROF_PCIE_TX_BYTES,      counter, The number of bytes of active pcie tx data including both header and payload.
DCGM_FI_PROF_PCIE_RX_BYTES,      counter, The number of bytes of active pcie rx data including both header and payload.

the two metrics above are bot shown as counters, so everytime protheus collects data it monotonically increase the value accordingly.
so in theory it seems as if we are required to match the scraping interval of prometheus and request interval of dcgm-exporter to the speed of pcie and nvlink. 
I could not find any other interpretation or reference or any other information reguarding these metrics.
Am I interpreting these metrics correctly?

And do those above logic apply to following metrics as well?
DCGM_FI_PROF_NVLINK_TX_BYTES
DCGM_FI_PROF_NVLINK_RX_BYTES

Can anyone please help me? any guidance or link to reference is very much appreciated!
thank you in advance.

**Comment by nikkon-dev** [comment]
@Omoong,

Please take a look here https://docs.nvidia.com/datacenter/dcgm/2.3/dcgm-user-guide/feature-overview.html#profiling
Those are definitely not counters and should be changed to gauges.
The same is valid for DCGM_FI_PROF_NVLINK_TX_BYTES.

WBR,
Nik

**Comment by Omoong** [comment]
@nikkon-dev 

well they are set as counters in your csv files
please, take a look at 
https://github.com/NVIDIA/dcgm-exporter/blob/574d63d717af9a4447092070d9501ec1eb83873e/etc/dcp-metrics-included.csv#L77

so line 77 and 78 should be changed to gauge?

and 

DCGM_FI_PROF_NVLINK_TX_BYTES
DCGM_FI_PROF_NVLINK_RX_BYTES

should also be set as gauges?

**Comment by Omoong** [comment]
@nikkon-dev 

Also, i dont know if this is the right place to ask, but even in the guide you linked me to confused me because of the difference in the wording.

on the direct page you linked me to shows the following
![image](https://user-images.githubusercontent.com/79127715/181700930-8d848e8b-f1ce-4aec-a189-c2927cd3c7fd.png)

although its not exactly the same page but in the dcgm user guides that also link to api reference theres is a field identifiers tab under modules that show 
![image](https://user-images.githubusercontent.com/79127715/181701544-d09582ee-1b32-4f6d-b48a-e53115e0c7bb.png)

for me the confusion came from
1. number and rate
2. including header and payload and other describing not including header.

link to the second picture's page is following
https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html
as you can see you can also follow into the page that show the same information you have linked above 
this just seems like an updated page.
https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#profiling-metrics

**Comment by nikkon-dev** [comment]
@Omoong,

Thank you for pointing out the inconsistency in the documentation.
The correct wording is "rate." The wrong wording came from the comments in the header files, which were not correctly updated to reflect current behavior.

We will fix the wording.

WBR,
Nik

**Comment by Omoong** [comment]
@nikkon-dev 
could you also check the following metrics as well?
# DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL, counter, Total number of NVLink flow-control CRC errors.
# DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL, counter, Total number of NVLink data CRC errors.
# DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL,   counter, Total number of NVLink retries.
# DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL, counter, Total number of NVLink recovery errors.
DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL,            counter, Total number of NVLink bandwidth counters for all lanes.
# DCGM_FI_DEV_NVLINK_BANDWIDTH_L0,               counter, The number of bytes of active NVLink rx or tx data including both header and payload.

descriptions for these values are empty even in the api reference documents. 

also, is there a way to clear xid errors in the dcgm-exporter?
Specifically DCGM_FI_DEV_XID_ERRORS metric.
once 45 or 43 is set the value does not reset. Although its more of a warning, once the user notices the xid error 43 or 45 the user should be able to clear the xid error thus dropping the value back to 0, but it seems that the xid error number stays.
Is this a normal behavior? or Am i missing a step to clear the xid error?

**Comment by Omoong** [comment]
@nikkon-dev
sorry for being impatient...
but can i get any suggestions or anything for the 2 issues in the previous comments if any??
Thank you again!
