### ISSUE TITLE
GPU Tesla T4 哪些工具支持业务进程显存监控？

### ISSUE THREAD

**Issue by kelonsen** [NVIDIA/dcgm-exporter#98]
产品：目前使用英伟达 Tesla T4显卡
问题：
目前通过 nvidia-smi 可以看到显存大小和某个进程使用的显存大小；
[https://files.51wyq.cn/tmp/image001.png](https://files.51wyq.cn/tmp/image001.png)

通过gpu exporter 也可以监控到每个显卡显存的动态使用情况，
[https://files.51wyq.cn/tmp/image002.png](https://files.51wyq.cn/tmp/image002.png)

由于我们是多个进程同时使用一块显卡，无法检测到进程的显存动态使用情况。
请问有什么工具可以直接检测进程的显存使用情况，希望某个进程的显存使用情况也可以绘制成图，请问有没有现成工具（我们目前用了kubernets），谢谢！
[https://files.51wyq.cn/tmp/image003.png](https://files.51wyq.cn/tmp/image003.png)

**Comment by kelonsen** [comment]
[dcgm-exporter](https://github.com/NVIDIA/dcgm-exporter)，我看只能监控GPU Device，不能监控运行在GPU Device上业务进程/业务POD的显存使用情况。

**Comment by nikkon-dev** [comment]
@kelonsen,

dcgm-exporter does not provide any process attribution to the metrics. You could use DCGM directly to get job statistics. 
You could see an example of SLURM integration here https://developer.nvidia.com/blog/job-statistics-nvidia-data-center-gpu-manager-slurm/
